### ISSUE TITLE
Entered data in the identity field (Identify user form) disappears after minimizing the app if don't keep activities is enabled

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5922] opened 2024-01-18 09:29 UTC
#### ODK Collect version
the store version 2023.3.1, the master version f46374638fb3023330f152cf716752f5accce077
#### Android version
10, 13
#### Device used
Redmi 9T, Pixel 6a
#### Problem description
If don’t keep activities setting is enabled in the device data entered in the "Enter identity” dialog (in Identify user form) disappears after minimizing the app.
#### Steps to reproduce the problem
1. Don’t keep activities is enabled in the device.
2. Open to Identify user form.
[identify-user-audit.xml.txt](https://github.com/getodk/collect/files/13974620/identify-user-audit.xml.txt)
3. While on "Enter identity” dialog enter something in the identity field.
4. Minimize the app and go back to the app.
#### Expected behavior
The data entered in a field should be present after minimizing and going back to the app

**Comment by seadowg** [comment] 2024-01-25 13:21
Good find! I don't think we'll ever prioritise this. My assumptions here are:

- We expect the content of the field to be short
- We don't expect the user to need to switch apps midway through entering text into the field

@alyblenkin probably for you good to have a quick think about this to see if you disagree with me. For the moment I'll mark as "won't fix" and close.

**Closed as not planned by seadowg** 2024-01-25 13:21 UTC
Labels: won’t fix

**Comment by alyblenkin** [comment] 2024-01-26 18:21
Yes, this is another good find, but seems like a low priority. 

> * We expect the content of the field to be short

Yes, I agree! 

> * We don't expect the user to need to switch apps midway through entering text into the field

I can't reproduce it on my phone, but people may switch apps to check WhatsApp or get a phone call midway through entering text. I assume that wouldn't be super common, but I could see it happening. 

I also noticed this text field is darker than the others, making the blue label text challenging to read.

<img width="701" alt="Screenshot 2024-01-26 at 10 20 05 AM" src="https://github.com/getodk/collect/assets/7871340/f17b3b12-fb26-4c57-97fd-3080dfd4f1a9">

**Comment by seadowg** [comment] 2024-02-05 12:57
> I also noticed this text field is darker than the others, making the blue label text challenging to read.

Good spot! It was designed and built way before we added proper Material text fields to form entry. Could you create an issue with the changes you think we should make? I'm guessing the ["Change reason" feature](https://docs.getodk.org/form-audit-log/#reason-for-changes) will probably also want updating.
