### ISSUE TITLE
User is moved to main screen if user minimizes app on 'Reset result' dialog and returns to ODK in specific way

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1280] opened 2017-07-27 11:09 UTC
#### Software and hardware versions 
Collect v1.8
Android 4.2, 4.4, 5.1, 6.0

#### Problem description
User is moved to main screen if user minimizes app on 'Reset result' dialog and returns to ODK via menu with all installed apps or ODK icon in desktop

#### Steps to reproduce the problem
1. User goes to 'Admin Settings'
2. User opens 'Reset application' 
3. User selects what to reset and clicks on 'Reset'
4. 'Reset result' dialog appears
5. User minimize app 
6. User opens app from menu with all installed apps OR from desktop:  ![screenshot_20170727-115724](https://user-images.githubusercontent.com/3907554/28667419-bb6fbade-72cb-11e7-891e-4287244c0f39.png)
 ![screenshot_20170727-115709](https://user-images.githubusercontent.com/3907554/28667418-bb6fb9b2-72cb-11e7-9868-efcb6b555f30.png)
7. User sees ODK logo
![screenshot_20170727-114523](https://user-images.githubusercontent.com/3907554/28667584-72784da4-72cc-11e7-8585-af08bcb5e97d.png)
8. User is moved to main menu
9. If user clicks on device back button, user is moved to view with 'Reset result' dialog

#### Expected behavior
- User sees 'Reset result' dialog

#### Other information 
Problem is not visible when user returns to app via list of all opened apps:
![screenshot_20170727-115735](https://user-images.githubusercontent.com/3907554/28667445-d7af9548-72cb-11e7-9fdc-99d919213109.png)
Discovered during testing [#1269](https://github.com/opendatakit/collect/pull/1269)

**Comment by lognaturel** [comment] 2017-07-27 16:48
Wow, good one! I'm not able to reproduce it in Android 5.1.1, though. Do I need to do something special before reopening Collect? I tried waiting for a couple of minutes and locking the device. Both times I was able to see the reset dialog still there.

**Comment by lognaturel** [comment] 2017-07-28 04:32
I was able to reproduce once on Android 7.0 but it's not happening every time. Strange issue.

**Comment by grzesiek2010** [comment] 2017-07-28 08:53
I spent some time investigating this strange behavior and:
1. I can't see anything helpful in logs
2. The problem takes place only if I build the app - > copy the file to a device and install the app
3. **Everything is ok if I install the app using Android Studio or if I install the app from the store**
4. It's not related to dialogs, you can open any other view: eg. you can open form list then minimize your app and you should notice the same issue
5. Looks like there was a similar issue: https://github.com/opendatakit/collect/issues/1142 I think it's the same as I said it's not related to any particular view.

I decided to check out another app as it's really odd and I noticed the same behavior (works well if I install it using Android Studio and the problem takes place after installation from a file).

So it's not our problem and I think we can close the issue. Maybe we should add a short note in https://github.com/opendatakit/collect#troubleshooting

**Comment by lognaturel** [comment] 2017-08-03 19:41
So strange! You're right that it sounds just like #1142. 

@grzesiek2010 please submit a pull request to add a note to troubleshooting when you have a chance, that's a great idea.

**Closed as completed by lognaturel** 2017-08-03 19:41 UTC
Labels: bug

**Comment by hassnain0** [comment] 2024-08-15 16:36
The binary version of its metadata is 1.9.9999, expected version is 1.7.1. , Hey Everyone When I try to build release apk it throw me this I change kotlin version also Any solution
