### ISSUE TITLE
Error-level log messages for normal conditions

### ISSUE THREAD

**Issue by dcbriccetti** [getodk/collect#811] opened 2017-04-01 01:27 UTC
Here’s an example:
```
Log.e(t, "Creating PROGRESS_DIALOG");

.../org.odk.collect.android E/FormEntryActivity: Creating PROGRESS_DIALOG
```

Change to info or debug, or whatever is appropriate.

**Comment by rijuldhir** [comment] 2017-04-01 08:45
Sure will be on it.

**Comment by rockydcoder** [comment] 2017-04-01 16:53
@lognaturel @dcbriccetti 
I fixed this. Please review and merge.

**Comment by rijuldhir** [comment] 2017-04-01 18:27
@rockydcoder It is nice that you want to contribute to it but I have already done it and going to open PR. So you should close this PR and try another issue.

**Comment by rockydcoder** [comment] 2017-04-01 18:54
@rijuldhir , I did not see this issue being assigned to you, so I raised the PR. And I pushed the changes 2 hours before you did. In fact, I am not sure about the rules. May be @lognaturel can help us with that.

**Comment by rijuldhir** [comment] 2017-04-01 19:11
@rockydcoder I have been here for a while now and I was the one who asked for the issue but if you want you can ask @lognaturel

**Comment by lognaturel** [comment] 2017-04-03 16:17
@rijuldhir @rockydcoder Generally the first person to comment, in this case @rijuldhir, should be the one to address the issue. 

In this case, this is a broader problem found across the codebase and I will modify the issue to reflect that. Additionally, we have ongoing work to switch all `Log` calls to `Timber` in #562. I think it will be easier to make this change carefully across the codebase once we are on `Timber`. That will allow the person doing this across the codebase to be systematic in the use of `debug` vs. `info`, for example. We do generally recommend allowing for a bit of discussion before taking on an issue.

**Comment by rockydcoder** [comment] 2017-04-03 16:57
Okay, cool.

**Comment by dcbriccetti** [comment] 2017-04-03 18:13
Sorry, gang. Perhaps I was too hasty in opening the issue.

**Comment by lognaturel** [comment] 2017-04-03 18:14
@dcbriccetti No, the issue is no problem! It just so happens that it's related to a bunch of other things in progress in this case.

**Comment by dcbriccetti** [comment] 2017-04-03 18:16
No, I meant, had I been more attuned to the happenings I would have known the issue would be taken care of.

**Comment by lognaturel** [comment] 2017-06-03 00:17
I think the right strategy for this now that we have Firebase Crash set up is to look at exceptions that are being logged at very high frequency, file them as issues is they're real crashes and change the log level if not.

Currently @grzesiek2010, @yanokwa and I are the only ones with Firebase Crash access but I think it would be fine to give read-access to someone who would be interested in taking this on! @grzesiek2010 maybe you can also do some when you need a break from more difficult tasks!

**Comment by dcbriccetti** [comment] 2018-02-10 22:27
Can this be closed?

**Closed as completed** 2018-02-12 00:15 UTC
