### ISSUE TITLE
Wrong theme applied after locking the screen in landscape view when there are different color modes in the device and Collect 

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5288] opened 2022-09-19 09:26 UTC
#### ODK Collect version
v2022.1.0
#### Android version
Android 10, 11, 12
#### Device used
Xiaomi Redmi T, Samsung Galaxy M12, Pixel 3a

#### Problem description

When there are different color modes set in a device and in Collect app (e.g. phone is in the dark mode and Collect is in the light mode) locking the screen in horizontal position while a form is opened causes applying the wrong theme in the following questions and other parts of the app.
If the user rotates the screen, the correct theme is applied after that.

#### Steps to reproduce the problem
1. In device settings choose the dark mode.
2. Go to Collect app and in settings choose the light mode.
3. Open All widgets form.
4. Go to any question.
5. Rotate the screen so it is in the landscape view.
6. Lock the screen.
7. Unlock the screen.
8. Swipe to the next question.

#### Expected behavior
Following questions should be visible- correct theme is applied. 
#### Other information 
I’ve checked Android 13 on the emulator and the issue doesn’t occur on the emulator.

**Comment by seadowg** [comment] 2022-10-05 14:45
Again, I think this is a duplicate of #4836.

**Closed as completed by seadowg** 2022-10-05 14:45 UTC
Labels: theme-related
