### ISSUE TITLE
Date Widget displaying incorrect regional formatting for eg.Canada with YYYY/MM/DD style

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1532] opened 2017-10-12 10:52 UTC
#### Software and hardware versions 
Collect current master

#### Problem description
https://en.wikipedia.org/wiki/Date_format_by_country

Regional data formatting is correct for countries with DD/MM/YYYY and MM/DD/YYYY styles like United States or United Kingdom
![usa](https://user-images.githubusercontent.com/3907554/31492455-62073a0a-af4b-11e7-9ff8-cc7a16f8b1ad.png)
![uk](https://user-images.githubusercontent.com/3907554/31492457-63c3fb8a-af4b-11e7-9e03-2e710c3f8e5d.png)

But for country with YYYY/MM/DD style the formatting is incorrect
![canada](https://user-images.githubusercontent.com/3907554/31492525-b48b1972-af4b-11e7-8d47-4a4a56a3e13f.png)

#### Steps to reproduce the problem

1. User uses device where language is set to English (Canada)
2. User adds answer for data widget

#### Expected behavior
User sees correct regional formatting

**Comment by grzesiek2010** [comment] 2017-10-12 12:24
@mmarciniak90 @lognaturel I took a quick look at this issue and:
1. We use [DateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html) so even if there is something wrong it's most likely on their side.
2. I can't even reproduce the issue because my Galaxy S4 doesn't have English (Canada) language.
3. I tested Lithuanian since they use the same format and everything is ok so it might be related to some devices only or as I said to [DateFormat](https://docs.oracle.com/javase/7/docs/api/java/text/DateFormat.html).

I'll try to debug the project using your device @mmarciniak90 tomorrow since only your device has English (Canada) option. Maybe it returns Locale.US despite the fact you set Canada?

**Comment by grzesiek2010** [comment] 2017-10-13 08:49
@mmarciniak90 @lognaturel 
We use this code https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/utilities/DateTimeUtils.java#L15
I debugged the project and the issue takes place because of two problems:
1. As I said above even If I have English (Canada) language when I try to get default locale `Locale.getDefault()` I get `en` not `en_Ca`;
2. Even if I hardcode `en_Ca` instead of using `Locale.getDefault()`, `getBestDateTimePattern()` returns the same format. looks like they don't support such a case. In the description of this method you can read:

> Returns the best possible localized form of the given skeleton for the given locale.

so it also indicates it might not to support all cases.

I think we can close this issue since it's not something really important and it's not on our side.

**Comment by lognaturel** [comment] 2017-10-18 18:50
I think this is because it's a short date format with a month abbreviation rather than a fully abbreviated date with slashes. As a Canadian, I think the date is fine. 😊

That said, the pickers should be in the order of the fully abbreviated date. Is that the case? So for en_Ca I think it should be yyyy mm dd

**Closed as completed by lognaturel** 2017-10-18 18:50 UTC
