### ISSUE TITLE
Language Name Wrong in User Interface Settings Version 1.8.1

### ISSUE THREAD

**Issue by wonderchook** [getodk/collect#1256] opened 2017-07-17 23:07 UTC
#### Software and hardware versions 
Collect v1.8.1 Android 7.0, Galaxy S6 <- Incorrect
Collect v1.8.1 Android 6.0.1, Ellipsis 8 <- Correct

#### Problem description
Language dropdown shows "Bahasa Indonesia" as "Indonesia" in some versions of Android. 

![screenshot_20170717-155958](https://user-images.githubusercontent.com/67992/28293604-bec8d8c4-6b09-11e7-97bd-1a4520ebaf68.png)

#### Steps to reproduce the problem
1. Open ODK-Collect
2. Click General Settings
3. Click User interface
4. Select Language
5. Scroll down and observe "Indonesia" 

#### Expected behavior
I would expect the drop down to say "Bahasa Indonesia" which is the correct name of Indonesian in the Indonesian language itself. I'm unsure if other languages are wrong, the ones I know appear to be correct.

**Comment by grzesiek2010** [comment] 2017-11-02 09:20
I was able to reproduce this issue and it depends on Android version. We just display available language name from `Locale`.

@lognaturel I think we can close this issue since it's not on our side.

**Closed as completed** 2017-11-02 15:21 UTC
