### ISSUE TITLE
Add acknowledgements screen

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#239] opened 2016-11-09 12:18 UTC
This is a pretty terrible oversight, but we should have some place in Collect where we list the open source code we use and maybe even the contributors.

https://www.bignerdranch.com/blog/open-source-licenses-and-android has a few options for how to do this.

**Comment by lognaturel** [comment] 2016-11-19 07:03
This should be as automated as possible. For example, use something like https://github.com/hierynomus/license-gradle-plugin or https://github.com/jk1/Gradle-License-Report to get the license text in a single document.

**Comment by jnordling** [comment] 2016-12-01 16:45
Maybe in the hamburger stack, and in github.
![screenshot_20161201-114302](https://cloud.githubusercontent.com/assets/11786919/20802912/8a2e9196-b7bb-11e6-9694-cd5716643016.png)

Does this list exist for ODK, in README.md's or anything. Im sure if the text was there it would be feasible to implement.

**Comment by grzesiek2010** [comment] 2016-12-14 09:31
I'll take it.

**Comment by grzesiek2010** [comment] 2016-12-15 18:27
I investigated how we can do that automatically and tested few plugins. Unfortunattely none works perfect for us.
https://github.com/hierynomus/license-gradle-plugin - pretty cool plugin but can't detect a type of license from our jar libraries. I discussed with author of this plugin and he confirmed that we have to mapp them manually - it's not convenient.
https://github.com/cookpad/license-tools-plugin - recognized only few libraries (don't know why)
https://github.com/jk1/Gradle-License-Report - don't know why but generates empty license file so doesn't work at all.
and several others as I remember but without success.

Additionaly I investigated some tutorials how to do that without any plugins (simillar to one mentioned by @yanokwa) and in my opinion it's better solution to implementing not perfect plugin and have to edit something manually in the future anyway. 
So I would like to implement one of the solutions from mentioned tutorials. We can add some aproprite information for developers to keep in mind they need edit the license file everytime they add/remove a library.

What do you think?
Can I go ahead and implement that?

**Comment by lognaturel** [comment] 2016-12-16 02:08
This makes me realize that I'm not sure why so many dependencies are packaged as jars rather than managed remotely. @yanokwa is there a reason that you know of? As far as I know, javarosa is the only one that needs to be packaged as a jar. @grzesiek2010 do you think getting remote dependencies through Gradle would make one of these plugins worth it? I've filed this as #296 so we can deal with it separately but if you think it will make the license managing easier it might be worth looking at first. That said, it looks like they mostly create a big text file of license info so that may not be so useful.

I also came across [this plugin](https://github.com/PSDev/LicensesDialog) which helps build the dialog itself and could either give good ideas or make the code cleaner.

A good next step would be to write up a quick proposal of how you want to implement it (html/webview? the plugin above? access from settings? access from hamburger stack?) so anyone who is interested can comment.

**Comment by grzesiek2010** [comment] 2016-12-16 07:58
> do you think getting remote dependencies through Gradle would make one of these plugins worth it?

I think currently there is no good plugin and we will have to add somthing manually anyway but it's good idea to do that #296 

> I also came across this plugin which helps build the dialog itself and could either give good ideas or make the code cleaner.

I tested this one, it's really good.

Ok I'll implement my proposal.

**Comment by yanokwa** [comment] 2016-12-16 12:50
The dependencies are packaged as jars because ODK Collect started in a time before maven/gradle were popular. Agreed that we should probably get rid of the jars, so thanks for filling #296, @lognaturel.

**Comment by grzesiek2010** [comment] 2016-12-18 19:29
I implemented my proposal so please look at this. I added new activity which use WebView so all the information are stored in html file.
![screenshot_2016-12-18-19-59-17](https://cloud.githubusercontent.com/assets/3276264/21295804/2248fb84-c55d-11e6-9c60-216f6ed53569.png)
![screenshot_2016-12-18-19-59-21](https://cloud.githubusercontent.com/assets/3276264/21295803/2245e390-c55d-11e6-8048-c7aa4568023a.png)
![screenshot_2016-12-18-19-59-28](https://cloud.githubusercontent.com/assets/3276264/21295802/22450a42-c55d-11e6-89d4-901f168daa56.png)

You can see the code: https://github.com/grzesiek2010/collect/commit/ede73469d3343c1b39a1fa710ae32e771c66f031
I'll improve that if you accept my proposal.
I think it's really nice and I would like to implement this solution, what do you think?

**Comment by lognaturel** [comment] 2016-12-18 21:21
Looks great to me! The only thing I don't love is where it's accessed from -- it's not that important so I don't think it should be the first thing someone sees in General Settings. I think maybe moving it down to the bottom after "Mapping options" in a new section called "About" would be nice. @yanokwa?

**Comment by yanokwa** [comment] 2016-12-18 21:41
I like the implementation! 

We will want to have an About activity that goes in the hamburger menu, but for now, the bottom is the right place to put it. 

Please add an `About` header at the bottom, and then put `Open source licenses` beneath that.

**Closed as completed** 2016-12-21 19:51 UTC
Labels: help wanted, bug
