### ISSUE TITLE
User is not moved to Track Changes Reason view after minimization

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3526] opened 2019-12-12 10:19 UTC
#### Software and hardware versions 
Collect master
Android 7.0, 9.0
Correct behavior on Android 5.1

#### Problem description
User is not moved to Track Changes Reason view after minimization

#### Steps to reproduce the problem
1. User edits a form which tracks changes [track-changes-reason-on-edit.xml.txt](https://github.com/opendatakit/collect/files/3955134/track-changes-reason-on-edit.xml.txt)
2. User sees view `Track Changes Reason`
3. User minimizes app
4. User opens Collect
5. User is not moved to `Track Changes Reason` view

#### Expected behavior
User is moved to `Track Changes Reason` view

**Comment by lognaturel** [comment] 2019-12-12 15:37
They're just back in the form edit view and need to trigger a save again to track the reason, right? If so, this doesn't seem like a big deal to me.

**Comment by lognaturel** [comment] 2019-12-12 15:42
@mmarciniak90, you probably have Do Not Keep Activities on, right?

**Comment by seadowg** [comment] 2019-12-12 17:02
@lognaturel @mmarciniak90 yeah I can't reproduce this without enabling "Don't Keep Activities". Unless you're seeing something different I'd potentially vote for closing this. Not sure we'd want to go to the both of making that work for that scenario.

**Comment by grzesiek2010** [comment] 2019-12-12 23:39
I agree it takes place only with `Don't Keep Activities`, we can close.

**Closed as completed by grzesiek2010** 2019-12-12 23:39 UTC
Labels: in progress

**Comment by mmarciniak90** [comment] 2019-12-17 10:03
I repeated this case and I confirm that's because of the `Don't Keep Activities` option. 
I'm sorry I missed it in the repro steps.

**Comment by seadowg** [comment] 2019-12-17 10:06
@mmarciniak90 no worries! It's nice to have it enabled to find weird edge cases but I wish the emulator made it visually obvious as I usually forget I switched it on. I've always thought a red banner (with "Don't keep activities enabled!") at the top of the screen would have been nice.
