### ISSUE TITLE
User is moved to main view if user minimizes app during filling form on Android 6.0 and 4.2

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1142] opened 2017-06-13 13:11 UTC
#### Software and hardware versions 
ODK Collect - current master
Problem is visible on Android v4.2.1 and v6.0
Problem is not visible on Android v5.1.1, v4.4.4, v4.1.2

#### Problem description
User is moved to main view when she/he minimizes during filling form

#### Steps to reproduce the problem
1. User opens form
2. User minimizes ODK Collect
3. User opens ODK Collect app again

#### Actual behavior
User sees main view

#### Expected behavior
User sees last filled question, on which she/he minimized the app.
User is not moved to other questions or views after minimization.

#### Other information 
Verified on v1.7.1 from Google Play and this problem is not visible

**Comment by shobhitagarwal1612** [comment] 2017-06-19 10:08
@mmarciniak90 I wasn't able to reproduce this bug on android 6.0 emulator.

**Comment by mmarciniak90** [comment] 2017-06-19 10:35
@shobhitagarwal1612 I verified on emulator and also I do not see this bug. 
I use the real device Samsung Z3 (D6603) with Android 6.0.1 and there the problem is visible.

**Comment by shobhitagarwal1612** [comment] 2017-06-19 10:36
@mmarciniak90 Thanks for confirming. I am downloading the Android 4.2 emulator for testing on that as well

**Comment by shobhitagarwal1612** [comment] 2017-06-19 11:01
There is a problem while installing apk in the android 4.2 emulator so someone with a physical device should look into this

**Comment by grzesiek2010** [comment] 2017-06-19 11:03
@shobhitagarwal1612 what's the problem? Any logs?

**Comment by shobhitagarwal1612** [comment] 2017-06-19 11:05
Both me and @lognaturel have been experiencing this problem with API 16 and API 17 emulators since past few weeks. The emulator shows that 'virtual sd card' is not available required for installing the app

**Comment by grzesiek2010** [comment] 2017-06-19 11:10
ok so I'll look at it using our real devices.

**Comment by grzesiek2010** [comment] 2017-06-20 08:14
I made a quick investigation yesterday and I was able to reproduce the issue using one of mentioned devices but interestingly only if I install the app using `.apk` file! Everything is ok if I install the app directly using Android Studio. So it's a bit strange. At first glance I wasn't able to see anything strange in logs as well. 
I'll try to investigate logs deeper and I'll check the beta version from the store.

**Comment by grzesiek2010** [comment] 2017-06-23 11:50
@lognaturel 
I can confirm that everything is ok if we install the app from Google Play or using Android Studio. The problem occurs only when I build the app on my own and only on some particular devices. So it's something really odd and I can't see anything helpful in the logs.

The most important thing is as I said it works if we use Google Play. I think we can close this issue.

**Comment by lognaturel** [comment] 2017-06-25 17:57
Really strange. I agree with @grzesiek2010, let's close for now and reopen if a user reports it.

**Closed as completed by lognaturel** 2017-06-25 17:57 UTC
Labels: bug, user experience
