### ISSUE TITLE
Error in build of project in android studio 3.0

### ISSUE THREAD

**Issue by yashLadha** [getodk/collect#1651] opened 2017-11-21 14:54 UTC
#### Problem description
Build gives error when imported the project in android studio.

#### Steps to reproduce the problem
Just build the project in Android Studio 3.0

#### Expected behavior
Successful build with no errors and warnings

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment] 2017-11-29 21:32
The issue is with the gradle upgrade. The upgrade also breaks several other things -- see discussion in #1645. For now, please keep working with the older gradle and if you have any ideas on how to fix failing tests with new gradle, share them on #1645.

**Comment by lognaturel** [comment] 2017-12-05 22:29
Closed by #1645

**Closed as completed by lognaturel** 2017-12-05 22:29 UTC
