### ISSUE TITLE
The launch screen after a crash isn't scrollable

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6388] opened 2024-09-02 12:23 UTC
#### ODK Collect version
the master version f38ba7ed24b2c810b8ddfe4aaf7bcbdefaf6bc19
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
The launch screen after a crash isn't scrollable. If the error message was too long it wouldn't be possible to tap "ok" to continue. Currently it's possible to reproduce it with the crash described below.
![crashvertical](https://github.com/user-attachments/assets/b44d3be9-4deb-4b92-b2a3-ba3b8a1400c7)
![crashsreen](https://github.com/user-attachments/assets/17861020-b6c1-43a4-95a8-58af88796ac4)

#### Steps to reproduce the problem
1. Scan the QR code of user "test" from https://staging.getodk.cloud/#/projects/56/app-users
2. Refresh the list of blank forms.
3. After the crash open Collect.
#### Expected behavior
I'm not sure which is expected: scrollable screen or wrapped error message.

**Comment by grzesiek2010** [comment] 2024-09-02 12:27
This is a duplicate of https://github.com/getodk/collect/issues/6292

**Closed as completed by grzesiek2010** 2024-09-02 12:27 UTC
