### ISSUE TITLE
Error in InstanceServerUploader

### ISSUE THREAD

**Issue by s13g3lb4um** [getodk/collect#2154] opened 2018-04-25 03:18 UTC
#### Software and hardware versions 
Collect v1.14.1, Android v6.0, Tablet Huawei
Collect v1.13.1, Android v4.4.2, Tablet Plumb
Collect v1.13.x (Personalized version for me), Android v6.0, Tablet Huawei
Collect v1.13.x (Personalized version for me), Android v4.4.2, Tablet Plumb
#### Problem description
InstanceServerUploader.java line 434:
- response = httpclient.execute(httppost, localContext);
```java
04-24 21:44:58.154 27338-27890/org.odk.collect.android I/InstanceServerUploader: org.opendatakit.httpclientandroidlib.NoHttpResponseException: 104.131.10.95:3030 failed to respond
                                                                                     at org.opendatakit.httpclientandroidlib.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
                                                                                     at org.opendatakit.httpclientandroidlib.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
                                                                                     at org.opendatakit.httpclientandroidlib.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.execchain.RetryExec.execute(RetryExec.java:88)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
                                                                                     at org.opendatakit.httpclientandroidlib.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
                                                                                     at org.odk.collect.android.tasks.InstanceServerUploader.uploadOneSubmission(InstanceServerUploader.java:426)
                                                                                     at org.odk.collect.android.tasks.InstanceServerUploader.processChunk(InstanceServerUploader.java:597)
                                                                                     at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:621)
                                                                                     at org.odk.collect.android.tasks.InstanceServerUploader.doInBackground(InstanceServerUploader.java:74)
                                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:307)
                                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:246)
                                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                     at java.lang.Thread.run(Thread.java:833)
```
#### Steps to reproduce the problem

Send a file to my own server of ona.io

#### Expected behavior

File sended successfully

#### Other information 
- Only the oldest form that is sent fails
- Three weeks ago this app worked perfectly
- I review the code of https://github.com/GeoODK/collect
  The project GeoODK uses the library httpclientandroidlib-4.2.1 
  ODK Collect uses httpclientandroidlib-4.5.2-2
  The code of GeoODK is diferent, but it does not generate error and send successfully the file 
- I modified the file InstanceServerUploader.java 
  Original file:
   ```java
   try {
                Timber.i("Issuing POST request for %s to: %s", id, submissionUri.toString());
                response = httpclient.execute(httppost, localContext);
                int responseCode = response.getStatusLine().getStatusCode();
                HttpEntity httpEntity = response.getEntity();
                messageParser = new ResponseMessageParser(httpEntity);
                WebUtils.discardEntityBytes(response);
                Timber.i("Response code:%d", responseCode);
                // verify that the response was a 201 or 202.
                // If it wasn't, the submission has failed.
                if (responseCode != HttpStatus.SC_CREATED
                        && responseCode != HttpStatus.SC_ACCEPTED) {
                    if (responseCode == HttpStatus.SC_OK) {
                        outcome.messagesByInstanceId.put(id, fail + "Network login failure? Again?");
                    } else if (responseCode == HttpStatus.SC_UNAUTHORIZED) {
                        // clear the cookies -- should not be necessary?
                        Collect.getInstance().getCookieStore().clear();
                        outcome.messagesByInstanceId.put(id, fail + response.getStatusLine().getReasonPhrase()
                                + " (" + responseCode + ") at " + urlString);
                    } else {
                        // If response from server is valid use that else use default messaging
                        if (messageParser.isValid()) {
                            outcome.messagesByInstanceId.put(id, fail + messageParser.getMessageResponse());
                        } else {
                            outcome.messagesByInstanceId.put(id, fail + response.getStatusLine().getReasonPhrase()
                                    + " (" + responseCode + ") at " + urlString);
                        }

                    }
                    cv.put(InstanceColumns.STATUS,
                            InstanceProviderAPI.STATUS_SUBMISSION_FAILED);
                    Collect.getInstance().getContentResolver()
                            .update(toUpdate, cv, null, null);
                    return true;
                }
            } catch (IOException e) {
                if (e instanceof UnknownHostException || e instanceof HttpHostConnectException
                        || e instanceof SocketException || e instanceof NoHttpResponseException
                        || e instanceof SocketTimeoutException || e instanceof ConnectTimeoutException) {
                    Timber.i(e);
                } else {
                    Timber.e(e);
                }
                String msg = e.getMessage();
                if (msg == null) {
                    msg = e.toString();
                }
                outcome.messagesByInstanceId.put(id, fail + "Generic Exception: " + msg);
                cv.put(InstanceColumns.STATUS, InstanceProviderAPI.STATUS_SUBMISSION_FAILED);
                Collect.getInstance().getContentResolver().update(toUpdate, cv, null, null);
                return true;
  }
  ```
  My file:
  ```java
  try {
                Timber.i("Issuing POST request for %s to: %s", id, submissionUri.toString());
                System.out.println("WTF 1 " + httppost + " % " + localContext);
                response = httpclient.execute(httppost, localContext);
                int responseCode = response.getStatusLine().getStatusCode();
                HttpEntity httpEntity = response.getEntity();
                messageParser = new ResponseMessageParser(httpEntity);
                WebUtils.discardEntityBytes(response);
                Timber.i("Response code:%d", responseCode);
                // verify that the response was a 201 or 202.
                // If it wasn't, the submission has failed.
                if (responseCode != HttpStatus.SC_CREATED
                        && responseCode != HttpStatus.SC_ACCEPTED) {
                    if (responseCode == HttpStatus.SC_OK) {
                        outcome.results.put(id, fail + "Network login failure? Again?");
                    } else if (responseCode == HttpStatus.SC_UNAUTHORIZED) {
                        // clear the cookies -- should not be necessary?
                        Collect.getInstance().getCookieStore().clear();
                        outcome.results.put(id, fail + response.getStatusLine().getReasonPhrase()
                                + " (" + responseCode + ") at " + urlString);
                    } else {
                        // If response from server is valid use that else use default messaging
                        if (messageParser.isValid()) {
                            outcome.results.put(id, fail + messageParser.getMessageResponse());
                        } else {
                            outcome.results.put(id, fail + response.getStatusLine().getReasonPhrase()
                                    + " (" + responseCode + ") at " + urlString);
                        }

                    }
                    cv.put(InstanceColumns.STATUS,
                            InstanceProviderAPI.STATUS_SUBMISSION_FAILED);
                    Collect.getInstance().getContentResolver()
                            .update(toUpdate, cv, null, null);
                    return true;
                }
            } catch (IOException e) {
                if (e instanceof UnknownHostException || e instanceof HttpHostConnectException
                        || e instanceof SocketException || e instanceof NoHttpResponseException
                        || e instanceof SocketTimeoutException || e instanceof ConnectTimeoutException) {
                    Timber.i(e);
                } else {
                    Timber.e(e);
                }
                String msg = e.getMessage();
                if (msg == null) {
                    msg = e.toString();
                }
                try {
                    Timber.i("RE Issuing POST request for %s to: %s", id, submissionUri.toString());
                    System.out.println("WTF 1RE " + httppost + " % " + localContext);
                    response = httpclient.execute(httppost, localContext);
                    int responseCode = response.getStatusLine().getStatusCode();
                    HttpEntity httpEntity = response.getEntity();
                    messageParser = new ResponseMessageParser(httpEntity);
                    WebUtils.discardEntityBytes(response);
                    Timber.i("Response code:%d", responseCode);
                    // verify that the response was a 201 or 202.
                    // If it wasn't, the submission has failed.
                    if (responseCode != HttpStatus.SC_CREATED
                            && responseCode != HttpStatus.SC_ACCEPTED) {
                        if (responseCode == HttpStatus.SC_OK) {
                            outcome.results.put(id, fail + "Network login failure? Again?");
                        } else if (responseCode == HttpStatus.SC_UNAUTHORIZED) {
                            // clear the cookies -- should not be necessary?
                            Collect.getInstance().getCookieStore().clear();
                            outcome.results.put(id, fail + response.getStatusLine().getReasonPhrase()
                                    + " (" + responseCode + ") at " + urlString);
                        } else {
                            // If response from server is valid use that else use default messaging
                            if (messageParser.isValid()) {
                                outcome.results.put(id, fail + messageParser.getMessageResponse());
                            } else {
                                outcome.results.put(id, fail + response.getStatusLine().getReasonPhrase()
                                        + " (" + responseCode + ") at " + urlString);
                            }

                        }
                        cv.put(InstanceColumns.STATUS,
                                InstanceProviderAPI.STATUS_SUBMISSION_FAILED);
                        Collect.getInstance().getContentResolver()
                                .update(toUpdate, cv, null, null);
                        return true;
                    }
                } catch (IOException r) {
                    if (r instanceof UnknownHostException || r instanceof HttpHostConnectException
                            || r instanceof SocketException || r instanceof NoHttpResponseException
                            || r instanceof SocketTimeoutException || r instanceof ConnectTimeoutException) {
                        Timber.i(r);
                    } else {
                        Timber.e(r);
                    }
                    String msg1 = r.getMessage();
                    if (msg1 == null) {
                        msg1 = r.toString();
                    }
                    outcome.results.put(id, fail + "Generic Exception: " + msg1);
                    cv.put(InstanceColumns.STATUS, InstanceProviderAPI.STATUS_SUBMISSION_FAILED);
                    Collect.getInstance().getContentResolver().update(toUpdate, cv, null, null);
                    return true;
                }
            }
  ```
  My file works fine... the error exist but resend the instance form works

**Comment by huangyz0918** [comment] 2018-04-28 03:39
I think you can open a pull request and submit your solution 😄

**Comment by lognaturel** [comment] 2018-09-17 23:36
@s13g3lb4um I will close this for now. If you'd like to submit a pull request that explains your change, please do! In the mean time, the current code works for both Ona and Aggregate users so it's not clear what the problem is. If you do isolate the bug, you could also file an issue that explains why you are getting a failure in your case.

**Closed as completed by lognaturel** 2018-09-17 23:36 UTC
