### ISSUE TITLE
Crash of the app after minimizing the app or locking the screen while map is loading on geojson form with thousand points used with Mapbox.

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5177] opened 2022-07-06 10:11 UTC
**Software and hardware versions**

Android All versions

**Problem description**

When Mapbox is used as a source of maps on geojson form and the map is loading, minimizing the app or locking the screen causes a crash of the app.

**Steps to reproduce the problem**

    1. Select Mapbox in Settings -> Maps 
    2. Download geojson form with thousand points 
[geojson.xml.txt](https://github.com/getodk/collect/files/9053826/geojson.xml.txt)
[thousand-points.geojson.txt](https://github.com/getodk/collect/files/9053827/thousand-points.geojson.txt)

    3. Click Select place
    4. Minimize the app/ Lock the screen
    5. Go back to the app
       
**Expected behavior**

Map should load. The app doesn’t crash.

**Other information**

Checked on geojson form with thousand points.Works well on Google Maps.

**Comment by seadowg** [comment] 2022-07-21 12:58
@dbemke is this present in v2022.2.3 and v2022.3 Beta 2? I think we should start specifying the exact versions tested in "Software and hardware versions" as otherwise we need to work out what the "current" version was when the issue was posted.

**Comment by dbemke** [comment] 2022-07-21 14:52
@seadowg I've just checked on Adnroid 11 v2022.3 Beta 2 -crash.  v2022.2.3 no crash;
on Android 8.1 v2022.3 Beta 2 crash,   v 2022.2.3 crash

**Comment by seadowg** [comment] 2022-07-21 14:58
@dbemke great thanks. Looks like this needs to be marked as a regression then as the crash doesn't occur in the last major release.

**Comment by seadowg** [comment] 2022-07-22 10:27
@dbemke I can't seem to reproduce this. Could you post the stack trace you're seeing when it crashes?

**Comment by dbemke** [comment] 2022-07-22 11:07
@seadowg  Maybe I shouldn't have called this a crash because there is a dialogue with that? 
![osmgeojson2](https://user-images.githubusercontent.com/56479916/180426757-f2e16445-4f2f-4cf1-b51a-f6cf9a23a251.jpg)
`022-07-22 12:45:02.311 951-26266/? E/ActivityManager: ANR in org.odk.collect.android (org.odk.collect.android/.activities.FormEntryActivity)
    PID: 19795
    Reason: Input dispatching timed out (f893103 org.odk.collect.android/org.odk.collect.android.activities.FormEntryActivity (server) is not responding. Waited 10000ms for FocusEvent(hasFocus=false))
    Parent: org.odk.collect.android/.activities.FormEntryActivity
    Load: 13.04 / 12.59 / 12.18
    ------ Current CPU Core Info ------
    - offline : 
    - online : 0-7
    - AP Temp = 413
                                 0           1           2           3           4           5           6           7
    ------------------------------------------------------------------------------------------------------------------
    scaling_cur_freq        806000      806000      806000      806000     2002000     2002000     2002000     2002000
    scaling_governor   energy_step energy_step energy_step energy_step energy_step energy_step energy_step energy_step
    scaling_max_freq       2002000     2002000     2002000     2002000     2002000     2002000     2002000     2002000
    ------------------------------------------------------------------------------------------------------------------
    ----- Output from /proc/pressure/memory -----
    some avg10=0.00 avg60=0.00 avg300=0.00 total=100544374
    full avg10=0.00 avg60=0.00 avg300=0.00 total=41932577
    ----- End output from /proc/pressure/memory -----
    
    CPU usage from 0ms to 5652ms later (2022-07-22 12:44:56.624 to 2022-07-22 12:45:02.276):
      222% 19795/org.odk.collect.android: 191% user + 31% kernel / faults: 196879 minor 2 major
      37% 951/system_server: 19% user + 18% kernel / faults: 7082 minor 4 major
      22% 617/surfaceflinger: 12% user + 9.9% kernel / faults: 766 minor
      0.6% 697/media.codec: 0.4% user + 0.2% kernel / faults: 19044 minor
      5.4% 4830/com.google.android.gms.persistent: 3% user + 2.4% kernel / faults: 1574 minor 286 major
      4.4% 574/vendor.samsung.hardware.camera.provider@4.0-service_64: 1.2% user + 3.1% kernel / faults: 4141 minor
      0.2% 688/media.extractor: 0.1% user + 0% kernel / faults: 6859 minor
      3.7% 561/android.hardware.graphics.composer@2.2-service: 2.3% user + 1.4% kernel
      0.1% 748/media.swcodec: 0% user + 0% kernel / faults: 7419 minor
      2.4% 21994/adbd: 0.7% user + 1.7% kernel
      2.1% 331/logd: 0.5% user + 1.5% kernel / faults: 40 minor
      1.5% 187/esgov:0: 0% user + 1.5% kernel
      1.4% 729/vendor.samsung.hardware.gnss@2.0-service: 0.5% user + 0.8% kernel
      1.4% 24632/logcat: 0.1% user + 1.2% kernel
      1.2% 669/cameraserver: 0.5% user + 0.7% kernel / faults: 107 minor
      1.2% 17603/kworker/u16:4-events_unbound: 0% user + 1.2% kernel
      1.2% 22185/kworker/u18:4-mali_jd: 0% user + 1.2% kernel
      1% 229/decon0: 0% user + 1% kernel
      1% 9628/android.process.acore: 0.7% user + 0.3% kernel / faults: 873 minor 4 major
      0.8% 1259/com.android.systemui: 0.7% user + 0.1% kernel / faults: 67 minor
      0.8% 8925/kworker/u18:1-ev_unbound_wq: 0% user + 0.8% kernel
      0.8% 9087/kworker/u16:2-samsung_mobile_device:b: 0% user + 0.8% kernel
      0.8% 19578/kworker/0:0-events: 0% user + 0.8% kernel
      0.7% 564/android.hardware.sensors@2.0-service.multihal: 0.1% user + 0.5% kernel
      0.7% 2724/com.sec.android.sdhms: 0.5% user + 0.1% kernel / faults: 90 minor
      0.5% 542/statsd: 0.1% user + 0.3% kernel / faults: 262 minor
      0% 545/zygote: 0% user + 0% kernel / faults: 11 minor
      0.5% 1427/videoeditor.videorecorder.screenrecorder: 0.3% user + 0.1% kernel / faults: 74 minor
      0.5% 1669/kworker/u16:1-kverityd: 0% user + 0.5% kernel
      0.5% 1931/com.samsung.adaptivebrightnessgo: 0.3% user + 0.1% kernel / faults: 24 minor
      0.5% 9276/com.android.bluetooth: 0% user + 0.5% kernel / faults: 253 minor 1 major
      0.3% 1/init: 0.1% user + 0.1% kernel
      0.3% 10/rcu_preempt: 0% user + 0.3% kernel
      0.3% 82/ion_system_heap: 0% user + 0.3% kernel
      0.3% 194/irq/138-11a0000: 0% user + 0.3% kernel
      0.3% 228/decon0-fsync: 0% user + 0.3% kernel`

**Comment by seadowg** [comment] 2022-07-22 11:09
> Maybe I shouldn't have called this a crash because there is a dialogue with that?

@dbemke No you're still correct! That's just Android itself telling you there's been a crash.

**Comment by seadowg** [comment] 2022-07-22 11:12
@dbemke are you able to reproduce this every time and consistently on different devices? It looks like a performance related crash to me - `ANR in org.odk.collect.android` (https://developer.android.com/topic/performance/vitals/anr).

**Comment by dbemke** [comment] 2022-07-22 11:29
@seadowg  (Collect v2022.3  Beta2) Andorid 11: 5 tries- 5 crashed, Android 8.1: 4 tries - 2 crashed

**Comment by seadowg** [comment] 2022-07-22 12:14
@dbemke looks like I can reproduce on Android 11 every time (like you're seeing)

**Comment by seadowg** [comment] 2022-07-23 12:29
I can't find an exact reason for this, but my theory is that adding markers one by one has finally caught up with us here and actually overloads something. I'll investigate adding markers all at once, like we've talked about before (#5087).

**Closed as completed** 2022-07-26 12:31 UTC
