### ISSUE TITLE
Mismatch error after finalizing forms, adding property in Central and refreshing list of blank forms

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6396] opened 2024-09-04 13:38 UTC
#### ODK Collect version
the master version f38ba7ed24b2c810b8ddfe4aaf7bcbdefaf6bc19
#### Android version
10, 14
#### Device used
Redmi 9T, Galaxy m23
#### Problem description 1
There's an error after finalizing a registration form, adding a property via Central and opening the update form after refreshing the list of blank forms
![PropertyAdded](https://github.com/user-attachments/assets/d795125d-38bb-4b1d-b4b6-359981f737ef)

#### Steps to reproduce
1. Download user cacti https://staging.getodk.cloud/#/projects/101/app-users
2. Set auto send to "off”
3. Fill and finalize the cactus registration form.
4. Go to Central and add a property.
5. In Collect refresh the list of blank forms
6. Open the cactus monitoring form.

#### Problem description 2
I encounter a mismatch error after the steps described below. It occurs in also in other entities update forms but with  different mismatch error (same steps). I wasn't able to reproduce it on Pixel 7a (Android 14). It might be connected with entities forms
 with spec 2024.1.0
 ![mismatch](https://github.com/user-attachments/assets/fa01ebb1-4b17-4e4d-9357-4a85f4db3456)

#### Steps to reproduce the problem
1. Download user cacti https://staging.getodk.cloud/#/projects/101/app-users to Collect.
2. Set auto send to "off".
3. Fill and finalize the cactus registration form.
4. Go to Cactus monitoring form and update the created entity. Finalize the form.
5. Go to Cactus monitoring form and update the same entity again. Finalize the form.
6.  In Central add a new property (+new).
![addProperty](https://github.com/user-attachments/assets/079d4794-d8dd-4d30-afbe-b0a995685a68)
7. In Collect refresh the list of blank forms.
8. Open the cactus monitoring form.

#### Other information
If apk from #6376 is used to reproduce the steps the error doesn't occur after the steps above.
A mismatch error occurs if you follow steps 1-8 and after that 
go to"Ready to send" and send all forms
Go to "Start new form" and refresh the list of blank forms
Open the cactus monitoring form
![sentRefresh](https://github.com/user-attachments/assets/f706453b-c0b1-4af0-8ab4-038cb25a10a5)

**Comment by seadowg** [comment] 2024-09-04 16:26
@dbemke the error only happens the first time you open the monitoring form right? If I close it and open it again the error doesn't happen (unless I add another property and refresh).

**Comment by seadowg** [comment] 2024-09-04 16:44
@dbemke I'm not able to reproduce using #6376. Could you double-check for me?

**Comment by dbemke** [comment] 2024-09-05 06:58
> the error only happens the first time you open the monitoring form right? If I close it and open it again the error doesn't happen (unless I add another property and refresh).

The error is while opening the monitoring form but later might also appear when you open the form for the second time and select the entity and swipe. 
We reproduced it on 3 devices but I don't know why the error never appeared on Pixel 7a

**Comment by dbemke** [comment] 2024-09-05 07:08
> I'm not able to reproduce using #6376. Could you double-check for me?

I'm guessing that this error appears only in "new" forms (spec 2024.1.0). Forms from 6376 use old spec. I'll start adding this info about forms in steps in new issues.

**Comment by seadowg** [comment] 2024-09-05 07:24
> Forms from 6376 use old spec. I'll start adding this info about forms in steps in new issues.

I'm not sure what you mean by this. How does that PR "use" old spec forms? I tried reproducing using that branch and I couldn't using the project linked here.

**Comment by dbemke** [comment] 2024-09-05 07:54
Now we have 2 "versions" of forms. The "old" entities forms and  "new" xml forms (for Central) with entities:entities-version="2024.1.0" and the trunkVersion, branchId part. It seems that this occurs only in "new" forms.
And there's the part/factor that the issue doesn't occur on all devices.

**Comment by seadowg** [comment] 2024-09-06 17:09
As [I've said in #6398](https://github.com/getodk/collect/pull/6398#issuecomment-2334477707):

> I'm going to abandon this particular line of investigation as the DB code has been changed by a few recent PRs. I think the next focus is to develop a new failing test against master.

More thoughts in the thread. But so far it seems like the only fix we have is to perform this query in `updateRowIdTable`:

```kotlin
databaseConnection.readableDatabase.rawQuery(
       """
       SELECT *, i.$ROW_ID
       FROM $list e, ${getRowIdTableName(list)} i
       WHERE e._id = i._id AND i.$ROW_ID = ?
       """.trimIndent(),
       arrayOf((-1).toString())
   ).use { it.moveToFirst() }
```

I think one idea (in addition to things explored and mentioned in #6398) would be to try and rework `#save` in some way. The new code is much simpler (removing transactions etc). I couldn't get that working in #6398, but it might be more successful with the new code.

**Comment by seadowg** [comment] 2024-09-09 07:24
I of course ended up having another theory pop into my head over the weekend and had to spend a wee bit of time looking into it. I'd got fixated on the problem being the `updateRowIdTable` approach as the `index` is where the bug presents itself, but I realized that the "Add new property" repro step is probably the only thing that makes this different from other flows we typically use and that there was probably something else up as I'd also run into problems playing around with `row_number()`.

Given that, I focused in on the `ALTER TABLE` operation. I tried playing around with using a different approach based on `SQLiteUtils.doesColumnExist` instead of our current "fire and forget" strategy for updating the list table schema and I immediately ran into problems: tests would fail because the code would try to add columns that did already exist. It seems to be that doing an `ALTER TABLE` with a shared connect (`SqliteOpenHelper`) can cause issues for subsequent queries via that same connection. I even managed to find a [StackOverflow that points to similar issues as we've run into](https://stackoverflow.com/questions/35922246/table-column-not-updated-after-alter-table-in-sqlite). It also just seems quite intuitive modifying a table's schema would cause problems for an open database connection.

I then tried moving our ["magic query"](https://github.com/getodk/collect/issues/6396#issuecomment-2334484877) from `updateRowIdTable` to after our `ALTER TABLE` call, and it fixed the failing tests I had. For me, this seems to confirm that that is the source of our problems. Because of that, we need to either avoid `ALTER TABLE`, do a connection reset/magic query after an `ALTER TABLE` or find a way to use Android's migration to add columns. It could also make sense to do an "upfront migration" (with a connection reset) before `#save` and have `#save` reject/fail if the properties don't match the existing schema. I'll experiment with these next to see if I can get a working implementation together.

**Closed as completed** 2024-09-10 12:21 UTC
