### ISSUE TITLE
Look into why "Sent" toast is slow

### ISSUE THREAD

**Issue by alyblenkin** [getodk/collect#6297] opened 2024-07-30 17:29 UTC
The toast after sending form makes submission feel really slow, like 3~ seconds to send. 

Is it really true we can’t tell if it’s sent? The sent count does update, maybe we could watch that somehow?

**Comment by lognaturel** [comment] 2024-10-10 20:37
Duplicate of https://github.com/getodk/collect/issues/6277

**Closed as not planned by lognaturel** 2024-10-10 20:37 UTC
