### ISSUE TITLE
issue with compact-2 and compact-3 

### ISSUE THREAD

**Issue by imran3may** [getodk/collect#956] opened 2017-04-22 16:10 UTC
Hello Github community,

I found an issue with compact-3 and compact-2 functions. Please find attached a sample form, on which there are three compact functions: "quickcompact" which is working perfectly, "compact-2" which I really need due to the type of the project I am working on, and I am trying to use "compact-2" with select multiple and issue with this is, if I select 3 options from the list and later if I want to deselect one, it doesn't work. And Problem with "compact-3", I am trying to use that with select_one question; however, I can select both of them. 

Please find attached the sample form and image files to test the form.

Thank you for you support
Imran
[image.zip](https://github.com/opendatakit/collect/files/949113/image.zip)
[sample_reporting_form.xlsx](https://github.com/opendatakit/collect/files/949114/sample_reporting_form.xlsx)

#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment] 2017-04-25 04:50
I believe this is a duplicate of #802 which is fixed in the next release coming out 4/29!

**Closed as completed by lognaturel** 2017-04-25 04:50 UTC

**Comment by imran3may** [comment] 2017-04-25 10:57
Hi Hélène,

This is kind of duplication however not completely as the issue with
multiple select was not mentioned on  #802
<https://github.com/opendatakit/collect/issues/802> , Options cannot be
deselected under compact, once selected by mistake for multiple select
questions.

Thanks,
Imran


A N M AL IMRAN (Imran)
Brossard, QC
Canada
Cell: +1 (438) 501 3576

**Comment by lognaturel** [comment] 2017-05-03 21:51
@imran3may Could you please quickly confirm that v1.6.1 from the Play Store now does what you expect?

**Comment by imran3may** [comment] 2017-05-03 22:41
Dear Hélène,

Amazing, it is working perfectly. My heartful *gratitude* to you and all
the developers contributing to ODK.

Regards,
Imran


A N M AL IMRAN (Imran)
Brossard, QC
Canada
Cell: +1 (438) 501 3576

**Comment by lognaturel** [comment] 2017-05-03 23:19
Yay, I'm happy to hear it's working now, @imran3may! 🎉
