### ISSUE TITLE
QR code is generated incorrectly and there is no way to scan it.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#4526] opened 2021-04-21 13:07 UTC
#### Software and hardware versions 
Collect master Android all, device used...

#### Problem description
I have noticed that qr code generated on the newest master does not contain valid settings and there is no way to scan it to other devices with Collect. It doesn't matter if the scanning device has a current master or any other version you still can't scan it. 

Collect's on the left side contain the same server change the right ones. The left one has been generated on yesterday's master. Both devices on the right have the newest code changes:
![1619007665276](https://user-images.githubusercontent.com/33342488/115555942-62c5b500-a2b0-11eb-9036-d207e053aede.jpg)

#### Steps to reproduce the problem
1. Install the newest Collect version on your device
2. Go to Admin Settings/Configure via QR code/ QR Code
3. Try to scan QR code with other devices

I have also tried with URL input manually, http, https, Google Drive and change the theme. 

#### Expected behavior
- User should be able to scan generated QR code

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by kkrawczyk123** [comment] 2021-04-21 13:09
@getodk-bot label "regression"

**Comment by seadowg** [comment] 2021-04-27 10:33
@grzesiek2010 are you able to take a look at this next? I'm imagining it's related to the settings changes, so you probably have the most context. Let me know if you think I'm wrong about that though!

**Comment by grzesiek2010** [comment] 2021-04-27 12:01
Yes, I'll try to take a look at it today.

**Comment by grzesiek2010** [comment] 2021-04-27 12:35
I can't reproduce the issue on the current master branch what I did was:
1. I installed ODK Collect (master branch) on two devices
2. Then I set the theme and server URL on one device
3. I scanned QR code from that first device

and everything was fine.

@kkrawczyk123 could you try again maybe there was something wrong but it's now fixed?

**Comment by kkrawczyk123** [comment] 2021-04-27 13:15
@grzesiek2010 I've just checked on the newest master and the issue does not occur anymore. It looks like it has been fixed even if unintentionally :)

**Closed as completed** 2021-04-27 13:19 UTC
