### ISSUE TITLE
Calculating a value based on previous questions doesn't work in a field-list

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#3450] opened 2019-11-15 14:41 UTC
#### Software and hardware versions 
Collect v1.24.1 and older versions

#### Problem description
Calculating a value based on previous questions doesn't work in a field-list

The problem has been originally reported on the forum: https://forum.opendatakit.org/t/auto-calculate-the-total

#### Steps to reproduce the problem
Try the attached form: 
[fieldListSimpleTest.xlsx](https://github.com/opendatakit/collect/files/3851887/fieldListSimpleTest.xlsx)

**Comment by lognaturel** [comment] 2019-11-15 22:56
This has been on my internal todo list for a while. I think it's probably a JavaRosa problem because it doesn't have to do specifically with field lists. See test `FieldListUpdateTest.changeInValueUsedInOtherField_ShouldChangeValue`.

**Comment by grzesiek2010** [comment] 2019-11-16 00:11
I think you are more familiar with this part of code as an author of the feature but from what I know about the code I beg to differ...

Let's assume we have a form with three integer questions in field-list
1. Number 1
2. Number 2
3. Total which has calculation (Number 1 + Number 2)

If you enter a number for Number 1 (50) and then for Number 2 (60) this happens:
1. Total is calculated in javarosa properly
2. It's a filed list so you want to refresh it so: 
In Collect we get answers for current screen:
50, 60, null (because the value has been calculated in javarosa but we don't have it on our side)
and we save it:
we save 50
then 60
and then null (clearing 110).

after saving them we try to rebuild the list but as I mentioned the value for total has been cleared.
So I think it's a problem on our side but might be wrong.

**Comment by lognaturel** [comment] 2019-11-16 04:59
Huh. According to my notes [visible_calculate.xlsx](https://github.com/opendatakit/collect/files/3853835/visible_calculate.xlsx) failed outside the `field-list` at some point as well but I can't reproduce on `master` so either I was wrong or something has changed. Anyway, if you see a quick fix, please go ahead and make sure to enable the existing test. If it's not quick, please leave aside for now and we can triage once the v1.25 issues are taken care of.

**Comment by lognaturel** [comment] 2019-11-16 18:49
Duplicate of #3211

**Closed as completed by lognaturel** 2019-11-16 18:49 UTC
Labels: in progress
