### ISSUE TITLE
Memory leak in MainMenuActivity

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2716] opened 2018-11-01 17:51 UTC
#### Software and hardware versions 
Collect v1.18.0

#### Problem description
Leak canary detects memory leak in `MainMenuActivity`

#### Steps to reproduce the problem
I don't know the exact steps of how to reproduce it but it happened while I was trying to remove a blank form and then coming back to the menu screen

#### Expected behavior
No leaks should happen

#### Other information 
Stack trace reported by Leak Canary suggests that the instance of `MainMenuActivity` is getting leaked through `MyContentObserver`

**Comment by shobhitagarwal1612** [comment] 2018-11-13 16:28
@opendatakit-bot claim

**Comment by shobhitagarwal1612** [comment] 2018-11-13 16:34
Screenshot of the memory leak:
![image](https://user-images.githubusercontent.com/8918023/48427989-0f221980-e790-11e8-897f-bca01d2afa46.png)

**Comment by shobhitagarwal1612** [comment] 2018-11-13 16:47
Steps to reproduce the bug:
1. Download a blank form
2. Open the form and save
3. Send finalized form
4. Remove the saved & blank form

I was able to see the memory leak by repeating the above steps 2-3 times

**Comment by lognaturel** [comment] 2019-10-04 15:09
It looks like this got lost in the shuffle! It would be good to see if it's still an issue.

**Comment by lognaturel** [comment] 2019-10-23 03:34
Confirmed that it's still an issue. See #3373 for related discussion.

I'm fairly certain that this can be fixed by calling `getContentResolver().unregisterContentObserver(contentObserver);` in `onDestroy`. Really, it would make more sense to register and unregister in `onResume` and `onPause`, I think.

**Comment by grzesiek2010** [comment] 2019-10-23 11:01
You are right about using `getContentResolver().unregisterContentObserver(contentObserver);` I started investigating it yesterday and today created a pr https://github.com/opendatakit/collect/pull/3414.

Moving the registration/unregistration required another fix I made in the [second commit](https://github.com/opendatakit/collect/pull/3414/commits/a88fda8e3173766f9204072539c54793ddb89062). It revealed a bug/bad implementation:
Saved forms should be counted in `onResume()` because if you go back from `FormEntryActivity` in most cases `MainMenuActivity` is just resumed not created again (assuming your device is not poor and doesn't kill it immediately). The problem wasn't visible before because we had kept the observer registered so even if `MainMenuActivity` was in the background the observer was called (for example if you are in `FormEntryActivity` and click the save icon) and the buttons were updated. it shouldn't work in that way. So now we unregister it in `onPause()` so it's not possible the observer is called when you are in `FormEntryActivty` and buttons are updated once you get back because I moved the code to `onResume()`.

**Closed as completed** 2019-10-30 17:12 UTC
Labels: in progress
