### ISSUE TITLE
Get Blank Forms: No useful feedback given on form download / parse failure

### ISSUE THREAD

**Issue by shawnsarwar** [getodk/collect#4345] opened 2021-01-12 15:56 UTC
#### Software and hardware versions 
Collect v1.29.3

#### Problem description
Previously when there was an issue with an XForm (like an invalid calculate bind) , collect would expose that error in the Download Results when attempting to download to that version of the form. As of 1.29.x the feedback is simply "Failed" which makes it more difficult to debug. There were no related errors in logcat either so the error just disappeared. 

#### Steps to reproduce the problem
Try to load the attached form in 1.27 & 1.29 to see the different behaviors.
[example.xml.txt](https://github.com/getodk/collect/files/5803229/example.xml.txt)
(Renamed to .txt because github doesn't allow XML attachments)
#### Expected behavior
I assume this is intended, but as stated it makes form issues harder to debug.

#### Other information 
I would find it helpful if either
 - a) the messages were replaced
 - b) OR errors log were maintained elsewhere in userland

**Comment by lognaturel** [comment] 2021-01-12 17:38
Thanks! Can you please describe your form design workflow? How are you ending up with invalid forms that weren't caught by your form design tool?

**Comment by shawnsarwar** [comment] 2021-01-13 09:45
Hi Helene, these are being generated from XLSForms via pyxform.

**Comment by lognaturel** [comment] 2021-01-13 21:46
In general, we design error messages for data collectors since those are the primary Collect users. We expect that form designers would validate their forms using ODK Validate (built into pyxform) and that data collectors would not hit form design issues on download.

Are you running `pyxform` at the command line? Have you disabled Validate? I can confirm that you have an extra comma in your `concat` statement but that gets caught by pyxform during the validation pass.

I'm going to close this issue because it's more of a form design issue. In the future, please start threads [on the forum](https://forum.getodk.org/c/support/6) so more community members can participate!

**Closed as completed by lognaturel** 2021-01-13 21:46 UTC

**Comment by shawnsarwar** [comment] 2021-01-14 11:43
I understand the separation, although I'd argue that exposing the results of validation you're already performing always provides a benefit. I'll open an issue on the server: https://github.com/eHealthAfrica/gather as it should certainly be picking this up if the functionality if included in pyxform.

**Comment by lognaturel** [comment] 2021-01-14 19:35
Sounds good!
