### ISSUE TITLE
date field issue after upgrading to v. 1.6.0 

### ISSUE THREAD

**Issue by dig360** [getodk/collect#996] opened 2017-05-02 13:54 UTC
#### Software and hardware versions 
Collect v1.6.0, Android 7.0 build 32.3.A.2.33, phone Sony Xperia Z5 Compact

#### Problem description
After upgrading to v 1.6.0, my form stop with an error message : 
![image](https://cloud.githubusercontent.com/assets/1770752/25620699/8efd602e-2f4f-11e7-80d7-93efab4c42a5.png)

#### Steps to reproduce the problem
Just use my already made forms

#### Expected behavior
date selection

#### Other information 
Sorry... I'm not tech...

**Comment by lognaturel** [comment] 2017-05-02 13:56
This is a duplicate of #995, please follow along there to get updates!

**Closed as completed by lognaturel** 2017-05-02 13:56 UTC
