### ISSUE TITLE
 Zebra MZ220 Printer Intergration with ODK collect issue

### ISSUE THREAD

**Issue by Khadomax** [getodk/collect#762] opened 2017-03-24 07:32 UTC
Please help me print barcode from an ODK Collect.
My Printer Zebra MZ220 is pairing through Bluetooth with an android device but it’s not printing through ODK collect.

From a different app, Zebra Print station printing is taking place.

Is there anything else we need to do to make this successful?

Stanley

#### Software and hardware versions 
Collect v1.x.x, Android vx.x.x, device used...

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment] 2017-03-24 14:49
Thank you for reporting this, @Khadomax. It is a duplicate of #752 so I will close this issue and ask you to please join the discussion there. We have not yet identified a developer with this kind of printer so it will be difficult to troubleshoot. Any additional information you can provide would be helpful. Is there any error show? Does Collect crash (close suddenly)? Has it ever worked with previous versions of Collect? Please share any extra information you have on #752 so we can try to identify the problem.

**Closed as completed by lognaturel** 2017-03-24 14:49 UTC
