### ISSUE TITLE
Unfortunately ODK has stopped'

### ISSUE THREAD

**Issue by kirstieJagoe** [getodk/collect#396] opened 2017-02-08 17:36 UTC
Collect v1.4.14, Android v4.4.2, device used (Itel, Huawei)

[BCC_Baseline_MainSurvey_ODK_FULL_STUDY_SW_v6 (1).xlsx](https://github.com/opendatakit/collect/files/761470/BCC_Baseline_MainSurvey_ODK_FULL_STUDY_SW_v6.1.xlsx)

**Problem description**
We can complete one screening survey and one main survey, then one screening survey but when come to second main survey we get the error message ' sorry , unfortunately ODK has stopped'.

**Steps to reproduce the problem**
We just need to enter data into  the survey forms twice over and the ODK stops.

**Expected behavior**
we expect it to move form survey to survey without issue and it doesn't seem to be able to do this. 

**Other information**
We have tried to reduce the programming and choices with no effect. The screening survey works without problem but it is short and simple. We have also tried different types of tablets with no effect. We dont seem to be able to upgrade the OSon the field team tablets higher than 4.4.2. However when using a tablet in Canada on android 5.0 we can not recreate the issue. 

We are now breaking the survey into different sections and testing each separately to see if we can ID where the issue is.

**Comment by yanokwa** [comment] 2017-02-09 04:07
Duplicate of #395.

**Closed as completed by yanokwa** 2017-02-09 04:07 UTC
