### ISSUE TITLE
Inconsistent behavior on QR Code scan with bad inputs

### ISSUE THREAD

**Issue by andrewsiew2** [getodk/collect#3529] opened 2019-12-13 07:07 UTC
#### Software and hardware versions 
Collect v1.24.1, Android v4.4.4, device used Nexus 7

#### Problem description
QR code either crashes or shows no Toast message on bad inputs.

On using "test" and "test123456789101112 " as QR Code inputs the scanner exits and there is no toast message indicating that the QR Code is invalid.

On using "test12345" the application crashes. A message saying "Unfortunately, ODK collect has stopped". When pressing the "OK" button. I get redirected to the main interface.

Note that the behavior is consistent on scanning and scanning via a downloaded image from the SD Card.

The QR Codes are generated from https://www.the-qrcode-generator.com/

#### Steps to reproduce the problem

1. Install Collect v1.24.1
2. Go to https://www.the-qrcode-generator.com/ and generate a QR Code with the given examples inputs
3. Go to Admin Settings > Import/Export Settings
4. Scan the QR Code
5. Notice the crash or lack of toast message
6. Press "OK"
7. Notice the redirect to the main interface

#### Expected behavior
It would be expected that any QR Code that has data that is not in the correct format would display an error informing the user the QR Code is invalid and without crashing the application. 

#### Other information 
Related Issue: https://github.com/opendatakit/collect/issues/2086

**Comment by lognaturel** [comment] 2019-12-14 03:28
Thank you, @andrewsiew2! If you want to claim it, please comment with `@opendatakit-bot claim` so no one else takes it.

**Comment by lognaturel** [comment] 2019-12-14 03:50
I think this is a duplicate of #2993, right?

**Comment by lognaturel** [comment] 2020-01-24 15:25
@devanshi7799 how about seeing if you can reproduce this? It sounds like @andrewsiew2 generated QR codes with raw strings rather than JSON. Broadly, it should be possible to scan any QR code and get a reasonable result.

**Comment by andrewsiew2** [comment] 2020-01-24 19:28
> I think this is a duplicate of #2993, right?

It's similar but in my case, it was just crashing.



> @devanshi7799 how about seeing if you can reproduce this? It sounds like @andrewsiew2 generated QR code’s with raw strings rather than JSON. Broadly, it should be possible to scan any QR code and get a reasonable result.

Also on this point, I feel like the code should also try to convert the string to a JSON or notify the user that it is not in format instead of crashing.

**Comment by lognaturel** [comment] 2020-01-24 19:29
> try to convert the string to a JSON or notify the user that it is not in format instead of crashing.

👍 A toast letting the user know that the QR code does not contain valid Collect settings would be great.

**Comment by chidauri** [comment] 2020-03-02 17:36
@lognaturel can i take this up?

**Comment by lognaturel** [comment] 2020-03-02 17:36
That would be wonderful, @chidauri. Please be sure to claim it!

**Comment by chidauri** [comment] 2020-03-02 17:43
@opendatakit-bot claim

**Comment by chidauri** [comment] 2020-03-03 09:32
@lognaturel i can't reproduce the issue in v1.25+  and i checked it was indeed present in v1.24.1.

**Comment by lognaturel** [comment] 2020-03-03 16:55
Great news, thanks for reproducing on both versions, @chidauri. Now I'm not sure why the issue stuck around!

**Closed as completed by lognaturel** 2020-03-03 16:55 UTC
Labels: help wanted, in progress
