### ISSUE TITLE
Select-one with compact-list appearance is not rendered properly

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#802] opened 2017-03-30 22:54 UTC
> We are working with ODK for some times and Now, with last version (1.5.1), We have a problem when settings a compact-list appearance for select-one question.

From gabriel.jugaro48@gmail.com
![45803475-5052-4fae-a37d-4415a99859b5](https://cloud.githubusercontent.com/assets/32369/24529523/f78f6a8c-1560-11e7-8764-b385d4673623.jpg)

**Comment by lognaturel** [comment] 2017-03-31 00:03
@grzesiek2010 I think you're the most familiar with this code these days, could you please take a look and see if you can find out what the problem might be? From the screenshot, I think the problem they're referring to is that multiple elements can be selected but I'm not sure.

**Comment by lognaturel** [comment] 2017-03-31 00:19
Also, @yanokwa has asked the person who reported the issue to attach a form so we can also wait for that!

**Comment by grzesiek2010** [comment] 2017-03-31 10:45
I wasn't able to reproduce the issue so let's wait for more information.

**Comment by jgrojas** [comment] 2017-03-31 16:32
Hi guys

Thanks for taking some minutes to take a look of this issue. Actually the question is a select_one type (See attached image) and when you switch the first selection it appears not to visual refresh the selection. if you advance to the next question and then return to que select_one question the appereance is showed correctly.

Thanks and regards. 

![image](https://cloud.githubusercontent.com/assets/9867658/24559534/ada73ab8-1604-11e7-96be-1c9ab996d369.png)

**Comment by jgrojas** [comment] 2017-03-31 16:46
I send the form in excel with the question.

Thanks...

[Error_select_one.xlsx](https://github.com/opendatakit/collect/files/886374/Error_select_one.xlsx)

**Comment by grzesiek2010** [comment] 2017-04-03 13:14
Interesting I'm still not able to reproduce the problem. I've found another similar issue - when we select something and then use "remove response" option an orange field is still visible but in that case I can see the problem in the code (I'll file the separate issue). 
@jgrojas could you add more info about device you use and your android version?

**Comment by lognaturel** [comment] 2017-04-03 15:51
@grzesiek2010 You know what just occurred to me? I think #679 fixed it. Could you please check out v1.5.1, verify that the problem is there, then checkout master to make sure that it's now gone?

I think the issue with clearing is addressed in #785.

**Comment by grzesiek2010** [comment] 2017-04-03 17:46
@lognaturel yes that's it we can close this issue.

**Comment by lognaturel** [comment] 2017-04-03 17:52
Thanks, @grzesiek2010! 

@jgrojas thank you for reporting this issue. The fix will be in April's release!

**Closed as completed by lognaturel** 2017-04-03 17:52 UTC
Labels: needs reproduction, needs information

**Comment by imran3may** [comment] 2017-04-25 11:10
multiple_select options cannot be deselected under compact, once selected.

**Comment by lognaturel** [comment] 2017-04-25 17:08
@imran3may That has also been addressed. The problem wasn't actually that it wasn't being deselected but that the user interface wasn't refreshing. In the version you currently have, you can tap on a selected item, swipe to the next question and swipe back to verify that the item was in fact unselected. It's the same thing with the select-one -- both weren't actually selected but the interface wasn't refreshing to show that.

**Comment by imran3may** [comment] 2017-04-25 17:38
Dear Hélène,

Thanks for the clarification.

Regards,
Imran


A N M AL IMRAN (Imran)
Brossard, QC
Canada
Cell: +1 (438) 501 3576
