### ISSUE TITLE
Text input

### ISSUE THREAD

**Issue by AbrahamMikolo** [getodk/collect#524] opened 2017-03-07 14:02 UTC
#### Software and hardware versions 
Collect v1.4.16, Android v4.3

#### Problem description
Behind the list of select, imported from external file, I have a text input. In the same page

#### Steps to reproduce the problem
I forked the last branch localy and make basic modification like icon, application name, minSDK, targetSDK

#### Other information 
Things you tried, stack traces, related issues, suggestions on how to fix it...
![screenshot_2017-03-07-17-01-22 1](https://cloud.githubusercontent.com/assets/13520559/23659640/ccbb1380-0357-11e7-89bc-9cd1da6eaa33.png)

**Comment by lognaturel** [comment] 2017-03-07 14:51
Can you please attach the form and external dataset that you are using and make it clear what the expected behavior is?

**Comment by AbrahamMikolo** [comment] 2017-03-09 05:41
I use the version code _1.4.6_, with the version 1.4.6, that I've downloaded from **google play**, this bug is not present. But I wont to modify the code.
Here is an example of **the form**
![form](https://cloud.githubusercontent.com/assets/13520559/23737419/09dd08ca-04a4-11e7-8717-c437c1be702d.jpg)

 in excel and **the external data**
![fkt_liste](https://cloud.githubusercontent.com/assets/13520559/23737432/1536f5be-04a4-11e7-8b2b-16c6e1eb7e4a.PNG)

**Comment by yanokwa** [comment] 2017-03-10 19:01
@AbrahamMikolo It's not clear what you are asking. I think the problem is that you are expecting a normal select and instead you are getting a select with a text box at the top reduces the options based on what you type. Is that correct?

Can you please include a small form (XLS and CSV) with one or two question that has this problem so we can reproduce it. Also, please test that form on the Google Play build of Collect and on the master branch without your changes.

**Comment by grzesiek2010** [comment] 2017-11-03 15:25
@lognaturel since we don't really understand the problem and we haven't received any new pieces of information for a few months I would vote for closing it.

**Comment by lognaturel** [comment] 2017-11-04 00:47
Ahh, I understand it now. It's because the `search` function used to exist but is now deprecated. I didn't know that at the time: https://forum.opendatakit.org/t/use-of-two-appearances/9443/3

@AbrahamMikolo `search` isn't supported anymore. If you read the thread above you will see other options for achieving what you need.

**Closed as completed by lognaturel** 2017-11-04 00:47 UTC
Labels: needs information
