### ISSUE TITLE
App crashes on Selfie Video and Image when permissions are disabled on specific Android 5.1.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2761] opened 2018-12-17 13:15 UTC
#### Software and hardware versions 
ODK Collect 1.18.2
Android v5.1.1 installed from https://forum.xda-developers.com/s7582/development/rom-cm12-1-galaxy-s-duos-2-trend-plus-t3225297
Samsung Duos 

#### Problem description
The user is able to inactive permissions on specific Android 5.1.1

#### Steps to reproduce the problem
1. Camera permission is set to 'Ignored'
2. User tries to get selfie image or selfie video
3. App crashes

#### Expected behavior
Permision dialog appears

|![screenshot_2018-12-17-13-59-22](https://user-images.githubusercontent.com/3907554/50089027-f11f5d00-0204-11e9-8d88-8bce30f5c4ad.png)|![screenshot_2018-12-17-13-59-55](https://user-images.githubusercontent.com/3907554/50089026-f11f5d00-0204-11e9-9a14-c5ae8931000d.png)|
|---|---|

#### Notes
* Back camera works properly

**Comment by muarachmann** [comment] 2018-12-21 19:10
@opendatakit-bot claim

**Comment by muarachmann** [comment] 2018-12-22 11:18
@mmarciniak90 how can i arrive at step one?? please my device isnt having that option i am tried navigating to app settings and odk cant see the ignore , allowed , always ask

**Comment by grzesiek2010** [comment] 2018-12-22 14:54
@muarachmann 
you can try creating a device using an emulator if your phone doesn't have that option.

**Comment by muarachmann** [comment] 2018-12-22 16:57
@grzesiek2010 suspected so cause i am on android 7.0 I will try creating the device pointed out by @mmarciniak90 in the issue and get to test

**Comment by muarachmann** [comment] 2018-12-24 13:49
@grzesiek2010 , @mmarciniak90 i just created two devices with version(Nexus 5X API 22 and Galaxy Nexus) 5.1 google play services. I cant still get the Privacy guard screen. Any help to the device i can create specifically?

**Comment by grzesiek2010** [comment] 2019-01-09 15:41
@mmarciniak90 
is that Privacy Guard a separate app or what?

**Comment by grzesiek2010** [comment] 2019-02-01 09:34
Ok, now I understand... Managing permissions is available on Android 6+
in this case, it's Android 5 but with [CyanogenMod](https://en.wikipedia.org/wiki/CyanogenMod) which allows editing permissions on older devices as well.
I think we shouldn't care about not official operating systems we have enough issues caused by differences between original firmware with different versions so that's enough.
I'm closing this issue.

**Closed as completed by grzesiek2010** 2019-02-01 09:34 UTC
