### ISSUE TITLE
Form subtext should be translated on the currently set language in Collect

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#3026] opened 2019-04-18 05:40 UTC
#### Software and hardware versions 
Verified Collect v1.19.0 and 1.21.1
Different behavior on Android version >= 7.0 and <= 6.0

#### Problem description
Form subtext should be translated on the currently set language in Collect

#### Steps to reproduce the problem
1. User sets the English language on Collect
2. User downloads form - form has `Added on ... ` information under the form name
3. User sets the Spanish language on Collect
4. User downloads form
5. User sets the French language on Collect
6. User downloads form

### Android 7.0 and newer
* `Added` is never translated
* Only date is translated

| | |
|---|---|
|![Screenshot_20190418-071240](https://user-images.githubusercontent.com/3907554/56338874-300df100-61ac-11e9-8c07-8cb4ad2117ee.png)|![Screenshot_20190418-071733](https://user-images.githubusercontent.com/3907554/56338879-3734ff00-61ac-11e9-8b74-9f5401aa327e.png)|

### Android 6.0 and older
* Subtext is translated on the language which was set during downloading

| | |
|---|---|
|![Screenshot_20190418-070843](https://user-images.githubusercontent.com/3907554/56338895-47e57500-61ac-11e9-90da-475f59565322.png)|![Screenshot_20190418-070853](https://user-images.githubusercontent.com/3907554/56338904-4fa51980-61ac-11e9-85cc-6c5340e9126c.png)|

#### Expected behavior
* The same behavior on all Android versions
* Subtext should be translated on the currently set language in Collect

**Comment by lognaturel** [comment] 2019-04-18 16:13
This is a duplicate of https://github.com/opendatakit/collect/issues/1419. I've closed that one in favor of this one since it has nice screenshots and context.

I had written:
> We will need to discuss how to approach this. First thing might be to try to understand why the information was saved as a string in the first place. Can that information be disaggregated into two fields (status and date/time)? Given that these strings currently exist in users' instance databases in whatever language, what would the migration path to the new schema be? Is it the case that the status is hardcoded to English? If so, that may make things easier. Another alternative might be to keep the existing column and use it if it's populated or use the two new columns if it's not.

**Comment by grzesiek2010** [comment] 2019-06-05 12:57
I think there is one solution here, we should display this text based on columns: `date` and `status`.
We do a similar thing with `Deleted on...` text:

![image](https://user-images.githubusercontent.com/3276264/58957843-cbc9df80-87a1-11e9-8b5e-2daf253c624f.png)

The text is created using `deletedDate` column which contains just dates:

![image](https://user-images.githubusercontent.com/3276264/58957734-85748080-87a1-11e9-9f4d-8c6ab9794611.png)

so we can remove the `displaySubtext` column at all.

It's not a risky change.

@lognaturel 
do you agree?

**Comment by lognaturel** [comment] 2019-07-01 16:34
Apologies for missing your latest update, @grzesiek2010. Are you absolutely sure that the `date` column represents the last time the status was changed? Are changes to the two columns always coupled? If so, then indeed that seems like an ideal solution.

**Closed as completed** 2019-07-16 09:53 UTC
Labels: in progress
