### ISSUE TITLE
Header on `Open source libraries and licences` view is not always visible on Android 4.1

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1959] opened 2018-03-02 09:10 UTC
#### Software and hardware versions 
Collect v1.13.1 
Android 4.1

#### Problem description
Header on `Open source libraries and licences` view is not always visible

#### Steps to reproduce the problem
1. User goes to `About` view
2. User clicks on `Open source libraries and licences` view
3. Header is not always visible

![screenshot_2018-02-28-12-07-34](https://user-images.githubusercontent.com/3907554/36784585-dc0f965a-1c77-11e8-82d1-0af24888b06a.png)

#### Expected behavior
* Header is always visible

#### Other information 
On v1.13.1 problem is visible about 1 of 10 attempts.
With changes from #1940 it is visible on 1 of 3 attempts.

**Comment by ArmenApresyan8** [comment] 2018-03-02 18:02
Couldn't reproduce it on Android 4.1 emulator.

**Comment by manishakeim** [comment] 2018-03-12 13:30
@opendatakit-bot claim

**Comment by manishakeim** [comment] 2018-03-14 08:03
@opendatakit-bot unclaim

**Comment by itzzritik** [comment] 2018-03-19 03:36
claim

**Comment by itzzritik** [comment] 2018-03-19 03:36
@opendatakit-bot claim

**Comment by itzzritik** [comment] 2018-03-19 03:40
@mmarciniak90 I Can't find this issue in actual application, header is always visible,
can you help me solving this issue ?

**Comment by itzzritik** [comment] 2018-03-19 03:46
Consider this ![screenshot](https://user-images.githubusercontent.com/24320496/37577127-f7f9b3d2-2b27-11e8-8757-76f86a246976.png)

**Comment by mmarciniak90** [comment] 2018-03-19 07:26
@ItzzRitik I user a real device, not emulator, Samsung Galaxy Young GT-S6310.
I checked this problem again and I'm able to reproduce it on v1.13.2.
To reproduce it I open this page few times because the problem is not visible always.

**Comment by itzzritik** [comment] 2018-03-20 14:54
@mmarciniak90 I executed on Redmi Note 4 Running on Oreo 8.1, I couldn't see it, anyways I'll see through it again and try to fix it, Thankyou for such quick reply.

**Comment by mmarciniak90** [comment] 2018-03-20 15:09
@ItzzRitik I noticed this problem only on Android 4.1, on device Samsung Galaxy Young GT-S6310

**Comment by itzzritik** [comment] 2018-03-21 05:48
@mmarciniak90  I worked on it to find solution, created new theme for activity, now its's working.
I don't have a device running on jellybean, but tested on emulator and it worked for me every time.
before merging I would like you to run application on your Samsung device, apk are attached here.

ThankYou.

[Download APP](https://github.com/opendatakit/collect/files/1832156/app.zip)
![Screenshot](https://user-images.githubusercontent.com/24320496/37695882-99d392e6-2cf8-11e8-9275-3e8e16961ce3.png)

**Comment by mmarciniak90** [comment] 2018-03-23 08:05
@ItzzRitik I installed your app on Samsung Galaxy Young GT-S6310 with Android 4.1 and the problem is still visible.
I see also some extra line 

| App with potential fix | Collect v1.13.1 |
|---|---|
| ![screenshot_2018-03-23-08-59-22](https://user-images.githubusercontent.com/3907554/37817956-6e8f3c38-2e70-11e8-834f-12aef0548cc7.png) | ![screenshot_2018-03-23-08-59-22](https://user-images.githubusercontent.com/3907554/36784585-dc0f965a-1c77-11e8-82d1-0af24888b06a.png)|

**Comment by itzzritik** [comment] 2018-03-30 20:14
@mmarciniak90 Sorry, but it was working on my emulator flawlessly, Running on Jelly bean - 4.1
as I can't test this issue myself, I'm un-claiming.
Thank you for your support.

**Comment by itzzritik** [comment] 2018-03-30 20:14
@opendatakit-bot unclaim

**Comment by lognaturel** [comment] 2018-04-06 21:05
Thank you very much for looking into this, @ItzzRitik! Since we only have one reproduction and it's not a terribly bad bug, @mmarciniak90 I propose we close this for now and reopen if anyone else can track it down.

**Comment by cooperka** [comment] 2018-10-16 02:36
@lognaturel should this be closed?

**Comment by lognaturel** [comment] 2020-02-05 18:47
Android <5 support will be dropped in v1.26 (https://github.com/opendatakit/collect/issues/3624).

**Closed as completed by lognaturel** 2020-02-05 18:47 UTC
Labels: help wanted
