### ISSUE TITLE
Delete Saved Form - misleadingly titled?

### ISSUE THREAD

**Issue by dimwight** [getodk/collect#4518] opened 2021-04-16 09:44 UTC
Wouldn't 'Delete Forms' be more accurate and user-friendly? It would
- better describe the screen itself
- not require a new user to guess that it handles blanks as well

(If this were agreed in principle I'd have a go at a PR.)

**Comment by seadowg** [comment] 2021-04-19 08:37
This is a duplicate of #3591 (although GitHub search had a hard time finding it so no worries there) so it would be good to continue the discussion in there. Please feel free to comment there with any problems you've been running into because of this!

**Closed as completed by seadowg** 2021-04-19 08:37 UTC
