### ISSUE TITLE
ODK Collect : Conditional questions and choice filtering not working when showing a group on same page

### ISSUE THREAD

**Issue by drik** [getodk/collect#1948] opened 2018-02-28 07:06 UTC
#### Software and hardware versions 
Collect v1.13.0, Android v7.0 device used Samsung J7...

#### Problem description
ODK Collect : Conditional questions and choice filtering not working when showing a group on same page
#### Steps to reproduce the problem
Create a form with group containing two question
Condition the second question to show if a certain value is selected in question 1
Put both question in the same group
Configure the group to show the questions on the same page
#### Expected behavior
When you select the value in first question that must prompt the second question, the second question is not showing up
#### Other information 
I created the forms with kobotoolbox (https://kf.kobotoolbox.org) and using ODK Collect for mobile collector

Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by lognaturel** [comment] 2018-03-01 18:12
Thanks for your interest in this issue, @drik! It's a duplicate of #378. Please track that one for progress made.

**Closed as completed by lognaturel** 2018-03-01 18:12 UTC
