### ISSUE TITLE
Search bar does not work as expected on view shared forms form Google Drive

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1910] opened 2018-02-22 14:52 UTC
#### Software and hardware versions 
Collect v1.12.2

#### Problem description
Search bar does not work as expected on view shared forms form Google Drive.

#### Use case 1
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`
3. User goes to `Shared with me`
4. User opens folder
5. User adds text to search bar
6. User clicks on search icon
7. User is moved to previous view with folder
![sharedsearchbar](https://user-images.githubusercontent.com/3907554/36544934-9a18ff8a-17df-11e8-88c8-6e0148b83bfd.gif)

#### Use case 2
1. User uses Google Drive as a server
2. User goes to `Get Blank Form`
3. User goes to `Shared with me`
4. User sees list of forms
5. User adds text to search bar
6. User clicks on search icon
7. Nothing happens

#### Expected behavior
* User sees forms which match the search

**Comment by ArmenApresyan8** [comment] 2018-02-22 15:05
@opendatakit-bot claim

**Comment by Diefenbaker** [comment] 2018-02-24 16:09
Hey, if it's ok I'd like to take a whack at this one? I've managed to reproduce the issue locally and will have some time over the next few days to do it.

**Comment by lognaturel** [comment] 2018-03-03 00:48
Closing this because it should be addressed in #1944.

**Closed as completed by lognaturel** 2018-03-03 00:48 UTC
Labels: help wanted, bug
