### ISSUE TITLE
Refactor the use of SharedPreferences 

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#1011] opened 2017-05-04 21:24 UTC
In general, the current approach of using shared preferences is not at all organised. We need a better approach to handle them across the entire codebase.

@lognaturel has some idea regarding this which was mentioned during a conversation in #collect-code which has been pasted below. 
> I haven't deeply considered it yet but it might be something we can represent as enums. Like a `CollectGeneralSettings` type and `CollectAdminSettings`. Then each one can have a key, a default, a corresponding `CollectAdminSettings` in the case of general settings..
`getEnumConstants` might be a way to approach getting a list of all preferences.

**Comment by lognaturel** [comment] 2017-05-04 22:18
To be fair to the current structure, I do think it's been fine for the existing needs! Adding barcode-based configuration in #781 means now having to iterate over all of the preferences and knowing their defaults. That's hard to do with the current structure.

[This article](https://medium.com/@ali.muzaffar/android-sharedpreferences-singleton-to-make-life-easier-f1d802b6cd8e) may also have some ideas.

**Comment by lognaturel** [comment] 2017-05-04 22:21
Oh, and I think @shobhitagarwal1612 wanted to take this one on after the QR code feature is merged so I'll mark it as "in progress."

Would be great to hear any ideas others may have!

**Comment by lognaturel** [comment] 2017-05-16 03:41
@shobhitagarwal1612 I just got the same exception as I had gotten before when launching the app after reading a barcode. I read a barcode with an admin password to try out #1027 and then I ran grzesiek2010:COLLECT-969_2. I thought the crash might have been related to reading a QR code and then downgrading to a version before the QR code feature but I did the same thing again from a clean install and am not getting the crash. I haven't yet looked at the code to see what the cause might be because this refactor would probably address it. What do you think, @shobhitagarwal1612, should we try to fix it as a separate issue or as part of this?

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.odk.collect.android/org.odk.collect.android.activities.SplashScreenActivity}: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
	at android.app.SharedPreferencesImpl.getBoolean(SharedPreferencesImpl.java:263)
	at org.odk.collect.android.activities.SplashScreenActivity.onCreate(SplashScreenActivity.java:90)
	at android.app.Activity.performCreate(Activity.java:6251)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
```

**Comment by shobhitagarwal1612** [comment] 2017-05-16 06:51
I think that this issue will be resolved by addressing the refactoring of the shared prefs. So, there is no need of opening another issue for resolving this.

**Closed as completed** 2017-05-25 04:05 UTC
Labels: in progress, refactor
