### ISSUE TITLE
Error logs while opening "All Widgets" Form

### ISSUE THREAD

**Issue by shobhitagarwal1612** [getodk/collect#2731] opened 2018-11-08 15:47 UTC
#### Software and hardware versions 
Collect v1.18.0, Android v8.1.0, Motorola G5 Plus...

#### Problem description
Below error is logged while opening `All-Widgets` form but app doesn't crash
```
2018-11-08 21:11:16.026 32244-2696/org.odk.collect.android I/FormDefCache: Attempting to load All widgets.xml from cached file: 5471c0a020c7bb6229b254390a6d8bd4.formdef.
2018-11-08 21:11:16.047 32244-2696/org.odk.collect.android E/FormDefCache: org.javarosa.core.util.externalizable.DeserializationException: No datatype registered to serialization code [d8 60 b9 d1]
        at org.javarosa.core.util.externalizable.ExtWrapTagged.readTag(ExtWrapTagged.java:100)
        at org.javarosa.core.util.externalizable.ExtWrapTagged.readExternal(ExtWrapTagged.java:63)
        at org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:217)
        at org.javarosa.core.util.externalizable.ExtWrapListPoly.readExternal(ExtWrapListPoly.java:54)
        at org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:217)
        at org.javarosa.core.model.GroupDef.readExternal(GroupDef.java:209)
        at org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:183)
        at org.javarosa.core.util.externalizable.ExtWrapBase.readExternal(ExtWrapBase.java:56)
        at org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:217)
        at org.javarosa.core.util.externalizable.ExtWrapTagged.readExternal(ExtWrapTagged.java:64)
        at org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:217)
        at org.javarosa.core.util.externalizable.ExtWrapListPoly.readExternal(ExtWrapListPoly.java:54)
        at org.javarosa.core.util.externalizable.ExtUtil.read(ExtUtil.java:217)
        at org.javarosa.core.model.FormDef.readExternal(FormDef.java:1177)
        at org.odk.collect.android.utilities.FormDefCache.deserializeFormDef(FormDefCache.java:120)
        at org.odk.collect.android.utilities.FormDefCache.readCache(FormDefCache.java:85)
        at org.odk.collect.android.tasks.FormLoaderTask.createFormDefFromCacheOrXml(FormLoaderTask.java:225)
        at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:126)
        at org.odk.collect.android.tasks.FormLoaderTask.doInBackground(FormLoaderTask.java:70)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2018-11-08 21:11:16.047 32244-2696/org.odk.collect.android W/FormDefCache: Deserialization FAILED! Deleting cache file: /storage/emulated/0/odk/.cache/5471c0a020c7bb6229b254390a6d8bd4.formdef
```

#### Steps to reproduce the problem
Goto `Fill Blank Form` and choose the `All Widgets` form 

#### Expected behavior
No error logs

**Comment by huangyz0918** [comment] 2018-12-11 12:47
I tried other kinds of form,  @shobhitagarwal1612. And I believe it's not a general issue, maybe caused by the xml form itself.
BTW, this error log comes from javarosa, should we open the issue there?

**Comment by grzesiek2010** [comment] 2018-12-11 13:41
@huangyz0918 

yes, probably the issue should be moved there. Could you do that? then we can close this one.

**Comment by huangyz0918** [comment] 2018-12-11 13:42
@grzesiek2010 sure, please close this. 😄

**Comment by huangyz0918** [comment] 2018-12-11 13:46
I saw there is a similar issue opened in javarosa, please see [here](https://github.com/opendatakit/javarosa/issues/245). I think we don't have to open a new one.

**Comment by grzesiek2010** [comment] 2018-12-11 13:50
@huangyz0918 You are right. Thanks!

**Closed as completed by grzesiek2010** 2018-12-11 13:50 UTC
