### ISSUE TITLE
Grey bar is not visible in GeoPoint widget when user opens widget again with saved location

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#2857] opened 2019-02-07 14:53 UTC
#### Software and hardware versions 
Collect v1.17, older versions were not be verified 
Google Maps

#### Problem description
Grey bar is not visible in GeoPoint widget when user opens widget again with saved location

#### Steps to reproduce the problem
1. User opens GeoPoint widget with Google map
2. User adds location and clicks on save icon
3. User opens GeoPoint widget again
4. **User sees that grey bar is not available**
5. User clicks on remove icon
6. Grey bar appears

| | | |
|---|---|---|
|Google Maps|![screenshot_2019-02-07-15-37-40](https://user-images.githubusercontent.com/3907554/52419231-fb1c5880-2aef-11e9-92ec-f11bc0716ec0.png)|![screenshot_2019-02-07-15-37-56](https://user-images.githubusercontent.com/3907554/52419241-ffe10c80-2aef-11e9-8e05-52cce0a5dc99.png)|
|OSM|![screenshot_2019-02-07-15-38-27](https://user-images.githubusercontent.com/3907554/52419274-08394780-2af0-11e9-9ec0-96ac7e245da8.png)|![screenshot_2019-02-07-15-38-44](https://user-images.githubusercontent.com/3907554/52419291-0cfdfb80-2af0-11e9-9a6f-caf47fdb82be.png)|

#### Expected behavior
* This behavior is visible only for Geopoint widget with Google maps
* Grey bar is always available

#### Other information 
Discovered while testing #2806

**Comment by huangyz0918** [comment] 2019-02-08 07:50
@opendatakit-bot claim

**Comment by zestyping** [comment] 2019-02-11 18:30
@mmarciniak90 As I understand it, the disappearance of the grey bar is intentional and by design.  The bar says "Long press to place mark...".  When there exists a saved location, the user cannot long-press to place a mark, so the instruction is not shown.  After the user deletes the saved location, it is then possible again to long-press to place a mark, so the instruction is shown.  Can you help me understand why you consider this to be a bug?

**Comment by huangyz0918** [comment] 2019-02-12 01:16
The behavior of OSM and the Google Map are inconsistent, the OSM has the bar but the Google Map has not. So I guess this is the reason why @mmarciniak90 consider it as a bug. @zestyping

**Comment by zestyping** [comment] 2019-02-12 08:13
@huangyz0918 Thank you for explaining, I understand.

This issue is obsolete now because the Google Maps activity and the OSM activity have been merged into a single activity after 1.17, so they now have the same behaviour.  The change in the user-visible behaviour of this grey bar is noted in the description of #2776, the PR that merges the two activities into one activity, where it says:

> * When the activity is launched with a previously saved point, marker dragging and long-press are initially disabled; the user must click the "trash" button to discard the point before adding/long-pressing/dragging a new marker.  Previously, the instructions "Long press to place mark to tap add marker button" would be displayed even though the user cannot do these things; now the instructions are not displayed.

**Comment by huangyz0918** [comment] 2019-02-12 08:18
@zestyping Thanks for explaining! So this issue is obsolete and should be closed. @mmarciniak90 , and I shall close #2859 too.

**Closed as completed** 2019-02-12 15:00 UTC
Labels: in progress
