### ISSUE TITLE
ArcWelder Broken Compatibility

### ISSUE THREAD

**Issue by yecarrillo** [getodk/collect#1023] opened 2017-05-15 16:21 UTC
#### Software and hardware versions 
Collect v16.1, Android emulation using ArcWelder ext on Chrome Windows , Windows 7 pro

#### Problem description
ODK Collect does not start
#### Steps to reproduce the problem
- Install Google Chrome
- Install ArcWelder ext https://chrome.google.com/webstore/detail/arc-welder/emfinbmielocnlhgmfkkmkngdoccbadn
- Download ODK Collect 1.6.1 https://opendatakit.org/downloads/download-info/odk-collect-apk
- Add APK to ArcWelder
- ArcWelder hangs with no response
#### Expected behavior
- ODK Collect Starts 

#### Other information 
- ArcWelder is a fantastic tool to test KoboToolbox forms, make demos, etc
- I tested previous versions of apks and the last ODK version compatible with ArcWelder is 1.5.1 (It starts normally)
- Other app I use daily with ArcWelder: IP Cam Viewer https://hit-mob.com/2015/04/08/run-ip-cam-viewer-on-mac-windows-linux-chromebook-using-chrome-and-arc-welder/

**Comment by lognaturel** [comment] 2017-05-15 20:45
@yecarrillo Any ideas on what might be causing it? If you could submit a pull request, that would be much appreciated.

**Comment by yanokwa** [comment] 2017-05-17 19:06
I don't know anything about ArcWelder, but given that 1.5.1 worked and 1.6.1 doesn't, I'd guess that the minification of APKs https://github.com/opendatakit/collect/pull/875 is the cause of the problem.

@yecarrillo Have you tried building a debug APK from source and using that? Debug builds are not minified, so that'd be the easiest way to test.

My preferred option for demos and testing forms is the [Android emulator](https://developer.android.com/studio/run/emulator.html). That's might also be a good workaround.

**Comment by lognaturel** [comment] 2017-06-01 01:44
@yecarrillo I'll close this for now since I don't think it's a Collect issue. Do let us know what you find out when you have a chance to try out a debug build!

**Closed as completed by lognaturel** 2017-06-01 01:44 UTC
Labels: needs information
