### ISSUE TITLE
Basic auth returns 401 Unauthorized

### ISSUE THREAD

**Issue by yanokwa** [getodk/collect#2520] opened 2018-09-03 20:43 UTC
#### Software and hardware versions 
Collect v1.16.4

#### Problem description
Connecting to an Aggregate server via basic auth does not work. 

#### Steps to reproduce the problem
1. Install the Aggregate VM and log into the CLI.
1. Install a text editor (e.g., `apt-get install vim`) and edit `/var/lib/tomcat8/webapps/ROOT/WEB-INF/classes/security.properties` to `security.server.deviceAuthentication` from digest to basic.
1. Configure the VM so you can [connect to external apps](https://docs.opendatakit.org/aggregate-vm/#connecting-to-the-vm-from-external-apps). This will also reboot Tomcat and apply the deviceAuthentication settings.
1. Log into Aggregate and set a test username and password.
1. Try to connect Collect to Aggregate using the credentials. Aggregate's logs will show a 401 (Unauthorized).

#### Expected behavior
According to https://docs.opendatakit.org/openrosa-authentication/, basic auth should work. Note that I'm doing this test with Aggregate v1.6.1 and no SSL certificates. I also do these tests on Collect by removing the username/password from the settings between trials and remove the app from memory.

#### Other information 
I'm sure the issue is with Collect because when I run `curl -i --header "X-OpenRosa-Version: 1.0" http://192.168.7.61/formList --user test:test` on my computer I get back the correct data.

**Comment by batkinson** [comment] 2018-10-25 15:13
The problem here is actually caused by two decisions that I feel are a bit nanny-ish (trying to force users behavior instead of educating and letting them make their own decision). They are:

- Basic authentication pre-emptive auth is only enabled if the URI scheme is 'https'
- The basic auth scopes only allow tcp port 443 or 8443

While I understand the spirit of these, I don't agree with the implementation approach. I would have much preferred a setting that I could disable to allow the more conventional behavior of not enforcing some policy on users expecting a generally useful networking stack. Another approach is to not prevent, but to warn - show visual feedback suggesting the setting is dangerous rather than preventing a valid  configuration (for development especially).

I have [a working fix](https://github.com/batkinson/collect/commit/25b855c6fe37cbe784d1fd9a4c4d7450a9b1ecab) that I am using locally. I can submit a PR if people are interested.

**Comment by xsteelej** [comment] 2018-11-26 22:38
Hi @yanokwa, I think this issue is because of the check to only do Basic auth over https. This 
has has been carried over with PR: https://github.com/opendatakit/collect/pull/2595.

Do we want to relax this rule?

**Comment by seadowg** [comment] 2020-08-11 09:37
When reworking the http layer of Collect we chose to stick with Basic over HTTPS only, so I'll assume we can close this for now and if any other discussions come up we can have them on the forum.

**Closed as completed** 2020-08-11 09:37 UTC
