### ISSUE TITLE
Range integer widget with vertical appearance

### ISSUE THREAD

**Issue by ArmenApresyan8** [getodk/collect#1906] opened 2018-02-21 22:56 UTC
#### Software and hardware versions 

Collect v 1.12.2
Android 7.0
Samsung Galaxy S6 edge

#### Problem description

The range integer widget's background disappears 

#### Steps to reproduce the problem

1) Choose any integer with the widget
2) Click next or swipe 
3) Go back to the widget

#### Expected behavior

The widget should stay the same

#### Screenshots
![28312706_1548379205275699_328520786_o](https://user-images.githubusercontent.com/18738136/36510293-f293d8e2-177b-11e8-98b4-48301e6d6f25.png)
![28407312_1548379681942318_1509607713_o](https://user-images.githubusercontent.com/18738136/36510297-f4b1c9a4-177b-11e8-95ec-164a73c3d261.png)

#### Other information 
I want to work on this issue

**Comment by lognaturel** [comment] 2018-02-22 01:08
Duplicate of #1262. @ArmenApresyan8 if you would like to look at that one, please comment with `@opendatakit-bot claim`.

**Closed as completed by lognaturel** 2018-02-22 01:08 UTC
