### ISSUE TITLE
required message not working

### ISSUE THREAD

**Issue by nap2000** [getodk/collect#787] opened 2017-03-29 01:01 UTC
#### Software and hardware versions 
Collect v1.4.16

#### Problem description
A custom required message is not showing when I try to skip a required question. Instead "Sorry, this response is required is shown"

#### Steps to reproduce the problem
1. Add message in required_message column of xlsform
2. Set question to required
3. Convert to XForm using http://opendatakit.org/xiframe/
4. Copy to android forms directory
5. Attempt to skip past the required question without answering

#### Expected behavior

The custom message is shown

#### Other information 

If you have a simple string as your message then it looks like the parseXPath function at line 916 in FormController expects an exception to be generated.   However an exception is not be generated and when the xPathRequiredMsg is evaluated it returns "";

**Comment by grzesiek2010** [comment] 2017-04-14 11:47
I investigated this problem and I was able to reproduce the issue but I'm not sure if it's on our side.
@nap2000 are you sure your problem is at line 916 in FormController as you described because I've noticed it's a few lines above and there is null here: https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/logic/FormController.java#L912
I've created a simple form using [ODK Build](https://build.opendatakit.org/) I've added only one question that is required and my custom required message. The form I've got is here:
https://pastebin.com/vNGaPv6E
Looking at the code I can see that we try to find the message using[ "requiredMsg"](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L1577) not "constraintMsg" like it is in form.
I've changed that manually:
https://pastebin.com/kv5Qp6ip
and everything is ok it works well.

@yanokwa @lognaturel is that our bug? because I don't now what should be used `constraintMsg` or `requiredMsg`.

**Comment by grzesiek2010** [comment] 2017-04-14 18:21
I would like to add that it doesn't work if I change ["requiredMsg"](https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/activities/FormEntryActivity.java#L1577) to `constraintMsg` in the odk code so looks like it should be `requiredMsg`. I wonder why there is `constraintMsg` if I use builder.

**Comment by nap2000** [comment] 2017-04-15 02:57
@grzesiek2010 Interesting. I can't reproduce the problem now using 1.5.1 and XLSForm.  Which is a bit baffling.  Maybe I imagined it.  

The line number was the rough location of the where I thought the problem was.  I tested in debug mode and stepped through the code.  It looked like the method XPathParseTool.parseXPath was returning a zero length string instead of throwing an exception when the message did not contain an xpath reference to a question value.

Ironic that you may have found an issue in ODK build but based on what you are saying and my further testing, I agree it doesn't look like it is a collect problem.

**Comment by yanokwa** [comment] 2017-04-18 22:38
I'm closing this issue because I used XLSForm and Collect and it works for me.

Also, there seems to be a bug in Build and I've filed it at https://github.com/opendatakit/build/issues/122.

**Closed as completed by yanokwa** 2017-04-18 22:38 UTC
Labels: bug
