### ISSUE TITLE
Crash on attempting to display error dialog if ODK directory can't be created

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3870] opened 2020-05-26 20:49 UTC
#### Software and hardware versions 
Collect v1.27.0, Android v7.0

#### Problem description
Crash on attempting to display error dialog if ODK directory can't be created

#### Steps to reproduce the problem
1. Create a /sdcard/odk/forms file which will block the creation of the odk directories
1. Launch Collect
1. The exception on directory creation attempt is caught but showing a dialog fails with:
```
2020-05-26 13:43:50.661 32248-32248/org.odk.collect.android E/DialogUtils: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
        at androidx.appcompat.app.AppCompatDelegateImpl.createSubDecor(AppCompatDelegateImpl.java:696)
        at androidx.appcompat.app.AppCompatDelegateImpl.ensureSubDecor(AppCompatDelegateImpl.java:659)
        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:552)
        at androidx.appcompat.app.AppCompatDialog.setContentView(AppCompatDialog.java:95)
        at androidx.appcompat.app.AlertController.installContent(AlertController.java:232)
        at androidx.appcompat.app.AlertDialog.onCreate(AlertDialog.java:279)
        at android.app.Dialog.dispatchOnCreate(Dialog.java:389)
        at android.app.Dialog.show(Dialog.java:293)
        at org.odk.collect.android.utilities.DialogUtils.showDialog(DialogUtils.java:87)
        at org.odk.collect.android.activities.SplashScreenActivity$1.granted(SplashScreenActivity.java:80)
        at org.odk.collect.android.utilities.PermissionUtils$1.granted(PermissionUtils.java:128)
        at org.odk.collect.android.utilities.PermissionUtils$11.onPermissionsChecked(PermissionUtils.java:305)
        at com.karumi.dexter.DexterInstance$1.run(Unknown Source)
        at com.karumi.dexter.MainThread.execute(Unknown Source)
        at com.karumi.dexter.DexterInstance.checkMultiplePermissions(Unknown Source)
        at com.karumi.dexter.DexterInstance.checkPermissions(Unknown Source)
        at com.karumi.dexter.Dexter.check(Unknown Source)
        at org.odk.collect.android.utilities.PermissionUtils.requestPermissions(PermissionUtils.java:273)
        at org.odk.collect.android.utilities.PermissionUtils.requestStoragePermissions(PermissionUtils.java:125)
        at org.odk.collect.android.activities.SplashScreenActivity.onCreate(SplashScreenActivity.java:73)
```

#### Expected behavior
Error dialog is shown.

#### Other information 
@seadowg you're currently touching related code, I think.

**Comment by seadowg** [comment] 2020-05-29 10:23
As far as I can see this is probably happening because the `SplashScreenActivity` just inherits from `Activity` rather than our `CollectAbstractActivity` or just simply `AppCompatActivity`. Looking at the history of this I'd imagine this bug has been there for a good while.

**Comment by grzesiek2010** [comment] 2021-01-11 22:39
It's a duplicate of https://github.com/getodk/collect/issues/4311 so I'm closing.

**Closed as completed by grzesiek2010** 2021-01-11 22:39 UTC

**Comment by lognaturel** [comment] 2021-01-11 22:40
Whoops, thanks.
