### ISSUE TITLE
Savepoints and instances are lost when using repeat section

### ISSUE THREAD

**Issue by toshniakshay** [getodk/collect#3379] opened 2019-10-08 09:41 UTC
**Device Details :** 
Samsung Galaxy J2 
RAM : 1GB
ROM : 8GB

- I have one form with 60 questions and also contains repeat section of 4 questions in between.
- Repeat section contains 2 questions 1 GPS quesiton, 1 single Select and 2 text quesitons.
- If I perform the repeat more than 40 times then application starts to slow down.
- After 60 times it takes around 10 seconds to load repeat section.
- After 90 times it takes around a min to load the repeat sections
- After 100 repeats application slows down big time and then application shows ANR(Application not responding)
- If I select close app option then all the data filled up till now is gone, all the savepoints are gone
- I think Android OS/ ODK wipes entire data in case of ANR. Not clear on this

**Technical Details :**
- On every repeat section FormController class's createNewRepeat() function is called.
- This function takes time to execute as the form size increases.
- As per my code understanding, on every repeat there is shallow copy of instance is done which copies instance. 
- Then for the repeat section template deep copy is perfomed and these newly created nodes are added to the instance.
- I added logs into the FormController.java's createNewRepeat() function and this confirms that the functioning happens under the hood is taking much time and as a result we face this performance hit.

**Note :** 
- I tried with simple form of only 4 repeat questions then in that case I was able to perform repeat sexctions over 300 times. Is there any limit on how much maximum repeat section or form can have questions?

**Questions :**
- How can I prevent the data loss in case of this kind of performance issue.
- Why data is getting wiped in this case.

**Comment by lognaturel** [comment] 2019-10-08 20:24
This looks like the same thing you wrote about at https://forum.opendatakit.org/t/savepoint-functionality-is-breaking-as-our-form-increases-in-length/22427, right? Can you please try in Collect from the Play Store and verify if you see the same issues?

I believe the slowdown happens because the whole form with all of its dependent logic is re-evaluated.

**Comment by toshniakshay** [comment] 2019-10-09 05:30
Thank you for the quick revert. I will perform some tests on play store build as well and see if I get same behaviour.

**Comment by lognaturel** [comment] 2019-11-16 18:47
This seems like it may be due to changes in the fork so closing until we get a reproduction on master.

**Closed as completed by lognaturel** 2019-11-16 18:47 UTC
