### ISSUE TITLE
Navigation buttons are not visible if user turns them on during filling form

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1574] opened 2017-10-30 13:20 UTC
#### Software and hardware versions 
Verified on Collect v1.11.0
Android 4.1, 4.2, 4.4, 5.1, 6.0, 7.0 

#### Problem description
Navigation buttons are not visible if user turns them on during filling form

#### Steps to reproduce the problem
1. 'horizontal swipes' option is selected in navigation
2. User starts filling form 
3. User opens General Settings
4. User goes to 'User Interface' options
5. User selects 'Use forward/backward buttons'
6. User clicks device back button to return to form
7. User is moved to form but buttons are not visible - user cannot move to other question

#### Expected behavior
User sees navigation button even if buttons were turned on during filling form.
Also other cases work immediately when navigation option is changed during filling form.

#### Workaround
Buttons appear when user changes device orientation

#### Other information 
Problem is not visible if 'Don't keep activities' option is turned on in Android Developer options

**Comment by grzesiek2010** [comment] 2017-10-30 14:10
@lognaturel
I think there might be even more bugs related to this case when we are able to change settings after opening the form. Do we really need this option there?

**Comment by codedsun** [comment] 2017-11-25 21:54
@grzesiek2010 @mmarciniak90 @lognaturel I want to work on this issue.

**Comment by codedsun** [comment] 2017-11-27 18:00
@lognaturel Can i work?

**Comment by lognaturel** [comment] 2017-11-27 18:07
This is an interesting one. I'm guessing that the option was put there to be able to change things like base maps while filling out a form. That works because the setting is read when the geo widgets are opened, not before. This one fails because the setting is read on form load. @grzesiek2010 in general my sense is that being able to change settings while filling out a form is useful but you're right that there are other issues. I'd prefer to fix the issue than to remove the possibility to change settings while filling out a form. What do you think?

@codedsun a good start might be to see what other settings cause problems. For example, setting the language brings you back to the landing screen which means you lose the data entered so far. I'm sure there are others like this buttons/swipe setting that should be updated when returning to the form. A list of these would be a good start followed by a proposed plan for addressing them coherently.

**Comment by grzesiek2010** [comment] 2017-11-27 18:13
@lognaturel yeah definitely it would be good to have such a list to decide what's next... if we have two issues (for example) we can fix them but if we have 10 maybe it's better to consider removing this option.

@codedsun it's a good first step if you want to take this issue.

**Comment by lognaturel** [comment] 2017-11-27 18:14
👍 Good point, @grzesiek2010. We'll have to see how many categories of problems there are.

**Comment by codedsun** [comment] 2017-11-27 18:15
@grzesiek2010 Assign it to me :+1:

**Comment by grzesiek2010** [comment] 2017-11-27 18:17
@codedsun 
you can do that by yourself just add a comment:

> @opendatakit-bot claim

**Comment by codedsun** [comment] 2017-11-27 18:17
@opendatakit-bot claim

**Comment by grzesiek2010** [comment] 2017-11-27 18:18
ooops I thought it doesn't work if it's a quote so:

@opendatakit-bot unclaim

Now it's only yours :smile:

**Comment by lognaturel** [comment] 2017-11-27 18:50
Haha, @grzesiek2010, for next time, putting it in backticks works -- `@opendatakit-bot claim`. 😊

**Comment by grzesiek2010** [comment] 2017-12-11 14:23
@codedsun any results? any problems?

**Comment by codedsun** [comment] 2017-12-11 20:30
@grzesiek2010 I got my motherboard crashed few weeks ago, then I shifted to the new system. I am getting back to it, sorry for the delay.Will start the work.

**Comment by codedsun** [comment] 2017-12-29 18:21
@opendatakit-bot unclaim

**Comment by grzesiek2010** [comment] 2018-01-17 10:31
Nothing new as I can see so I decided to investigate the issue on my own. The answer is: Yes the problem is related only to buttons and other options are well handled when we return from General Settings.

@opendatakit-bot claim

**Closed as completed** 2018-01-22 21:51 UTC
Labels: help wanted, bug
