### ISSUE TITLE
Add status indicator to show current position in form

### ISSUE THREAD

**Issue by akshay-ap** [getodk/collect#616] opened 2017-03-15 19:28 UTC
#### Software and hardware versions 
Collect v1.4.16, Android v4.4.2, device used...

#### Problem description
While filling form user is unaware of how much part of the form has been filled. The user experience can be improved if there is some indication of much form has been filled.
#### Steps to reproduce the problem
Choose Fill form button from Main menu of application.
#### Expected behaviour
Proposed improvement :array of Circular dots to show the current position of form. 
Below is the exact proposed implementation to be done. The bottom of each form will look like this.
![feature](https://cloud.githubusercontent.com/assets/16358982/23966914/1496b74a-09e3-11e7-813f-859ef15477ff.jpg)

![screenshot](https://cloud.githubusercontent.com/assets/16358982/23966918/1a68ba74-09e3-11e7-83c3-225009ad3f30.gif)

**Comment by pratikmjoshi** [comment] 2017-03-15 19:45
@akshay-ap This can be filed under issue #464, as it is a major ui improvement.

**Comment by lognaturel** [comment] 2017-03-15 20:06
@akshay-ap This is a good idea. Collect did previously have a progress bar but it was removed because it turned out to be very confusing with skip logic and repeats. How would you address that?

**Comment by pratikmjoshi** [comment] 2017-03-15 20:33
@akshay-ap This is a nice idea as it would provide a good sense of direction for the user.
However, I had tried using the circleindicator previously for an app, where data had to be stored as soon as it moved to the next view (just like collect) does, but I couldn't find a way to do so. Since circleindicator is linked to a viewpager, how would you propose to save the data as soon as the current question is swiped away?
Also, if we look at FormEntryActivity, views are dynamically created depending on the questions format. How would we know the number of circular dots(or the number of questions) beforehand?

**Comment by akshay-ap** [comment] 2017-03-16 16:24
I have thought of adding a popup-window.
It will contain Horizontal Linear-layout. Each element will be a circle. I bigger Circle will represent current position of the form which user is filling. On swiping the corresponding circle will be replaced with bigger one and older circle (Bigger one) will be replaced with a smaller one. The popup-window  will appear from start  (when onResume()  method of FormEntryActivity of  gets called) of activity and will disappear after onDestroy() method of FormEntryActivity of  gets called. This logic will require minimum changes in existing code. But I don't know how to find number of circles needed. Will this logic work?
It will look like this at bottom of the page.
![feature](https://cloud.githubusercontent.com/assets/16358982/23966914/1496b74a-09e3-11e7-813f-859ef15477ff.jpg)

**Comment by shobhitagarwal1612** [comment] 2017-03-16 16:35
What will happen wih the forms using repeats?

**Comment by saraswatmanu** [comment] 2017-03-17 10:33
I would like to point out one thing. The number of questions in a form can get really big in real life. Representing each swipe of question with a circle can be an issue here. Also how will the questions that involve branching logic be tackled?
One way I can think of is to group questions somehow and show progress in terms of percentage of questions completed in that group.

**Comment by grzesiek2010** [comment] 2017-03-17 10:40
I have and idea about repeat section. My proposal is to show a second progres bar when user is in repeat section. Then the main progres bar (for all questions) should be stopped and we can show the progres in repeat section using the second prgres bar. That second progres bar should be visible only if we are in repeats of course.

and @saraswatmanu is right of course it should be progres bar.

**Comment by pratikmjoshi** [comment] 2017-03-17 13:19
@grzesiek2010 Do you have any examples of a 2-progress bar procedure that you can post a  picture of here?

**Comment by grzesiek2010** [comment] 2017-03-17 13:29
No I don't it's only an idea I would prepare a small sketch but not today as I'm busy :)

**Comment by lognaturel** [comment] 2017-03-17 17:47
Please do make sure to search issues before filing new ones! This is a duplicate of #72.

**Comment by lognaturel** [comment] 2020-03-12 17:35
Close pending a spec.

**Closed as completed by lognaturel** 2020-03-12 17:35 UTC
Labels: user experience, needs discussion
