### ISSUE TITLE
Crash on Android 4.2 when open Selfie Image widget and Selfie video widget

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3234] opened 2019-07-24 10:13 UTC
#### Software and hardware versions 
Collect v1.23.x, Android v4.2.x, device used...

#### Problem description
Collect s crashing when open Selfie Image widget and Selfie video widget

#### Steps to reproduce the problem
1. Run Collect on Android 4.2 and swipe/jump to Selfie Image widget/Selfie video widget.

#### Expected behavior
App should not crash, user should be able to use both widgets. 

#### Other information 
07-24 12:00:10.813 24715-24715/org.odk.collect.android E/MessageQueue-JNI: java.lang.VerifyError: org/odk/collect/android/utilities/CameraUtils
        at org.odk.collect.android.widgets.ImageWidget.setUpLayout(ImageWidget.java:86)
        at org.odk.collect.android.widgets.ImageWidget.<init>(ImageWidget.java:61)
        at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(WidgetFactory.java:125)
        at org.odk.collect.android.views.ODKView.configureWidgetForQuestion(ODKView.java:216)
        at org.odk.collect.android.views.ODKView.addWidgetForQuestion(ODKView.java:172)
        at org.odk.collect.android.views.ODKView.<init>(ODKView.java:140)
        at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1185)
        at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1435)
        at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2670)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:600)
        at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1378)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1916)
        at android.view.View.dispatchPointerEvent(View.java:7435)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3610)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3538)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4790)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4750)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4902)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:125)
        at android.os.Looper.loop(Looper.java:140)
        at android.app.ActivityThread.main(ActivityThread.java:5297)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
        at dalvik.system.NativeStart.main(Native Method)
07-24 12:00:10.818 24715-24715/org.odk.collect.android E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.VerifyError: org/odk/collect/android/utilities/CameraUtils
        at org.odk.collect.android.widgets.ImageWidget.setUpLayout(ImageWidget.java:86)
        at org.odk.collect.android.widgets.ImageWidget.<init>(ImageWidget.java:61)
        at org.odk.collect.android.widgets.WidgetFactory.createWidgetFromPrompt(WidgetFactory.java:125)
        at org.odk.collect.android.views.ODKView.configureWidgetForQuestion(ODKView.java:216)
        at org.odk.collect.android.views.ODKView.addWidgetForQuestion(ODKView.java:172)
        at org.odk.collect.android.views.ODKView.<init>(ODKView.java:140)
        at org.odk.collect.android.activities.FormEntryActivity.createView(FormEntryActivity.java:1185)
        at org.odk.collect.android.activities.FormEntryActivity.showNextView(FormEntryActivity.java:1435)
        at org.odk.collect.android.activities.FormEntryActivity.onFling(FormEntryActivity.java:2670)
        at android.view.GestureDetector.onTouchEvent(GestureDetector.java:600)
        at org.odk.collect.android.activities.FormEntryActivity.dispatchTouchEvent(FormEntryActivity.java:1378)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1916)
        at android.view.View.dispatchPointerEvent(View.java:7435)
        at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3610)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3538)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4790)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4750)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4902)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:125)
        at android.os.Looper.loop(Looper.java:140)
        at android.app.ActivityThread.main(ActivityThread.java:5297)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by seadowg** [comment] 2019-08-23 16:05
@kkrawczyk123 I think this is a dupe of #3051. Does that look right?

**Comment by kkrawczyk123** [comment] 2019-08-26 06:07
@seadowg, yes it looks like it is.

**Comment by seadowg** [comment] 2019-08-26 10:11
Cool. I'll close this then!

**Closed as completed by seadowg** 2019-08-26 10:11 UTC
