### ISSUE TITLE
Pulling data from Aggregate FAILED: Forms that used to successfully indicate SUCCESSFUL are now indicating FAILED... Nothing has been changed from my end or on the Aggregate server. What could have happened? Initially when this problem started, I could still find my data had been pulled despite the report that pulling had failed but now it is actually totally FAILING and no data is being pulled

### ISSUE THREAD

**Issue by sadumah** [getodk/collect#377] opened 2017-02-03 02:03 UTC
<!-- 
Forms that used to successfully indicate SUCCESSFUL are now indicating FAILED... Nothing has been changed from my end or on the Aggregate server. What could have happened?
Initially when this problem started, I could still find my data had been pulled despite the report that pulling had failed but now it is actually totally FAILING and no data is being pulled !>

**Comment by yanokwa** [comment] 2017-02-03 02:40
Duplicate of #376.

**Closed as completed by yanokwa** 2017-02-03 02:40 UTC
