### ISSUE TITLE
Opening an instance with a time question and saving it without opening that question results in a one hour shift 

### ISSUE THREAD

**Issue by lognaturel** [getodk/collect#3305] opened 2019-08-09 19:44 UTC
https://forum.opendatakit.org/t/odk-collect-time-in-repeat-changes-on-submit/20966

@grzesiek2010 has reproduced. Does this actually only happen with Google Sheets?

**Comment by grzesiek2010** [comment] 2019-08-12 18:08
First of all, I need to point out that it's not a problem with repeatable groups (like described in the issue or on the forum). It's a broooooder problem which 
I can reproduce even with a simple time question like here:
[onlyTimeTest.xml.txt](https://github.com/opendatakit/collect/files/3493759/onlyTimeTest.xml.txt)

Steps (it's not something that everyone can reproduce because it depends on timezones/summertime/wintertime etc):
1. Open the attached form
2. Add any answer
3. Finalize the form
4. Open the saved instance (don't click on the question - important)
5. Go to the end of the form and save it
6. Open the saved form again - time will be changed +1h

it's not a regression as well, it's a long-standing issue which we should (or just could) have cought in the past, for example, working on other similar bugs like:
https://github.com/opendatakit/collect/issues/170 or https://github.com/opendatakit/javarosa/pull/12
we didn't because there is one tricky condition (step 4) when we open a saved form we can't open the question.

I debugged the project and here is the way it works:
1. I'm opening the form and setting current time let's say it's 00:41, the returned answer is: Sat Aug 10 00:41:00 GMT+02:00 2019
2. I'm finalizing the form. The value saved to the form is <time>00:41:00.000+02:00</time> (just the time of course since it's a time question not dateTime).
3. Then I'm opening the saved instance, javarosa takes the value from the form 00:41:00.000+02:00 and parses it with 01.01.1970 the result is Thu Jan 01 00:41:00 GMT+01:00 1970

ok let's compare now:
Aug 10 00:41:00 GMT+02:00 2019
Thu Jan 01 00:41:00 GMT+01:00 1970

the same hour so should be fine right? No, saving the answer I was in GMT+02 but in 01.01.1970 it's GMT+01 (because it's wintertime).

The case is even more interesting, even if we used let's say 01.08.1970 (should be summertime) it won't work because in 1970 in Poland we didn't have summertime at all.
More info:
https://pl.wikipedia.org/wiki/Czas_letni#Czas_letni_w_Polsce
it's only in polish but you can take a look at the table to notice there is a gap 1964-1977 where we had just our base time GMT+1

4. I'm saving the form again and it will save 00:41:00.000+01:00 where it was 00:41:00.000+02:00 before

so if I opened the form again javarosa takes 00:41:00.000+01:00 where I'm in GMT+02 so if it is 00:41 in GMT+01 it must be 01:41 in GMT+02 so set time to 01:41

why it works well if in step 4 if open the question? because TimeWidget parses the hour (which is ok itself, only GMT is different) with the current date what returns an appropriate value. 

I'm going to create a pr on the JR side which will fix the problem.

**Comment by grzesiek2010** [comment] 2019-10-04 09:48
it's fixed in https://github.com/opendatakit/javarosa/pull/478

**Closed as completed by grzesiek2010** 2019-10-04 09:48 UTC
