### ISSUE TITLE
Fix lints with "Deprecated" id

### ISSUE THREAD

**Issue by grzesiek2010** [getodk/collect#788] opened 2017-03-29 06:55 UTC
When you run ./gradlew lint, a report is generated at collect_app/build/reports/lint-results.html with potential problems with Collect. Find all with "Deprecated" id and fix those.

@sjain281297  are you interested in?

**Comment by SIMRAN1** [comment] 2017-04-01 10:58
I am intrested in solving this issue.Shall I proceed??

**Comment by grzesiek2010** [comment] 2017-04-01 12:12
@simran1 please go ahead

**Comment by SIMRAN1** [comment] 2017-04-01 13:50
@grzesiek2010  I have found 3 layouts with Deprecated resources,
27 files with  Deprecated API usage
6 obsolete gradle dependencies.
Do I have to change all of these?
Please give me a clear idea about what should I do?

**Comment by grzesiek2010** [comment] 2017-04-01 18:53
@SIMRAN1 follow the steps described above. You have to find all lints in that file with "Deprecated" id, as I remember there are about 7 lints in this category and all of them are related to layout files. Each lint is described so you can find out where is the problem (which file and which line).

**Comment by SIMRAN1** [comment] 2017-04-01 19:44
Thanks for the help.I will solve it.

**Comment by SIMRAN1** [comment] 2017-04-02 04:41
I have send a Pull Request for this issue

**Comment by lognaturel** [comment] 2017-04-03 19:26
I think this is a duplicate of #654?

**Comment by grzesiek2010** [comment] 2017-04-03 20:58
@lognaturel it's similar I have missed that one. Maybe I should have added comment about lints there. 
But #654 looks like abandoned - 18 days without any changes.

**Closed as completed** 2017-04-06 00:40 UTC
