### ISSUE TITLE
select_one on external csv file show autocomplet by default

### ISSUE THREAD

**Issue by mathieubossaert** [getodk/collect#1107] opened 2017-06-07 09:30 UTC
Hi,
first of all thank's a lot for the tool you create and maintain !
We are facing a bug with last odkcollect version(1.7.0)

When we set a select_one field on a csv file (etudes & protocoles), the ui shows the whole list (what we want) AND a text area to start typing for autocomplete (without 'autocomplete' in appearance column.

Here is the xml : 
```xml
<?xml version="1.0"?>
<h:html xmlns="http://www.w3.org/2002/xforms" xmlns:ev="http://www.w3.org/2001/xml-events" xmlns:h="http://www.w3.org/1999/xhtml" xmlns:jr="http://openrosa.org/javarosa" xmlns:orx="http://openrosa.org/xforms" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <h:head>
    <h:title>EXO_MOBILE_2_bis</h:title>
    <model>
      <instance>
        <exo_mobile_2bis id="exo_mobile_2_bis" version="2">
          <releve>
            <id_etude/>
            <id_protocole/>
            <code_releve/>
          </releve>
          <saisie_observateur jr:template="">
            <saisie_structure/>
            <search_observateur/>
          </saisie_observateur>
          <saisie_date>
            <date_obs/>
            <duree_obs/>
          </saisie_date>
          <meta>
            <instanceID/>
          </meta>
        </exo_mobile_2bis>
      </instance>
      <bind nodeset="/exo_mobile_2bis/releve/id_etude" required="true()" type="select1"/>
      <bind nodeset="/exo_mobile_2bis/releve/id_protocole" required="true()" type="select1"/>
      <bind nodeset="/exo_mobile_2bis/releve/code_releve" type="string"/>
      <bind nodeset="/exo_mobile_2bis/saisie_observateur/saisie_structure" type="select1"/>
      <bind nodeset="/exo_mobile_2bis/saisie_observateur/search_observateur" required="true()" type="select1"/>
      <bind nodeset="/exo_mobile_2bis/saisie_date/date_obs" required="true()" type="date"/>
      <bind nodeset="/exo_mobile_2bis/saisie_date/duree_obs" type="int"/>
      <bind calculate="concat('uuid:', uuid())" nodeset="/exo_mobile_2bis/meta/instanceID" readonly="true()" type="string"/>
    </model>
  </h:head>
  <h:body>
    <group appearance="field-list" ref="/exo_mobile_2bis/releve">
      <label>Informations sur le relevé effectué</label>
      <select1 appearance="search('etudes')" ref="/exo_mobile_2bis/releve/id_etude">
        <label>Etude</label>
        <item>
          <label>nom_etude</label>
          <value>id_etude</value>
        </item>
      </select1>
      <select1 appearance="search('protocoles')" ref="/exo_mobile_2bis/releve/id_protocole">
        <label>Protocole</label>
        <item>
          <label>libelle</label>
          <value>libelle_id</value>
        </item>
      </select1>
      <input ref="/exo_mobile_2bis/releve/code_releve">
        <label>Code du point de relevé</label>
      </input>
    </group>
    <group ref="/exo_mobile_2bis/saisie_observateur">
      <label>Observateurs du relevé</label>
      <repeat nodeset="/exo_mobile_2bis/saisie_observateur">
        <select1 appearance="quick search('structures')" ref="/exo_mobile_2bis/saisie_observateur/saisie_structure">
          <label>Structure de l'observateur</label>
          <hint>Saisissez une structure</hint>
          <item>
            <label>nom_structure</label>
            <value>id_structure</value>
          </item>
        </select1>
        <select1 appearance="quick search('observateurs','matches','id_structure', /exo_mobile_2bis/saisie_observateur/saisie_structure )" ref="/exo_mobile_2bis/saisie_observateur/search_observateur">
          <label>Observateur</label>
          <hint>Ajoutez un observateur</hint>
          <item>
            <label>nom_observateur</label>
            <value>id_observateur</value>
          </item>
        </select1>
      </repeat>
    </group>
    <group appearance="field-list" ref="/exo_mobile_2bis/saisie_date">
      <label>Date et durée du relevé</label>
      <input appearance="no-calendar" ref="/exo_mobile_2bis/saisie_date/date_obs">
        <label>Date de l'observation</label>
      </input>
      <input ref="/exo_mobile_2bis/saisie_date/duree_obs">
        <label>Durée de l'observation</label>
        <hint>en minutes</hint>
      </input>
    </group>
  </h:body>
</h:html>
```

**Comment by grzesiek2010** [comment] 2017-06-08 13:52
Hi @mathieubossaert thanks for reporting the issue. Could you also attach your csv file?

**Comment by mathieubossaert** [comment] 2017-06-09 07:48
Good morning,
of course, thanks a lot.
[exo_mobile_2bis-media.zip](https://github.com/opendatakit/collect/files/1063315/exo_mobile_2bis-media.zip)

**Comment by grzesiek2010** [comment] 2017-06-09 11:14
@mathieubossaert thanks for your attachments. I have been trying to reproduce the issue but I don't understand. 
You use search appearance `<select1 appearance="search('etudes')" ref="/exo_mobile_2bis/releve/id_etude">` and 
`<select1 appearance="search('protocoles')" ref="/exo_mobile_2bis/releve/id_protocole">`

so you can see the search box according to the implementation: https://github.com/opendatakit/collect/blob/master/collect_app/src/main/java/org/odk/collect/android/widgets/WidgetFactory.java#L180

What's wrong here?

**Comment by mathieubossaert** [comment] 2017-06-09 12:42
So I understand that both "search" and "autocomplete" appearence are synonym ?
I remember it was different but I must be wrong.

Sorry for the time you lost.

**Comment by grzesiek2010** [comment] 2017-06-09 12:46
@mathieubossaert yes it's the same I don't know why @yanokwa maybe you know something about it?

**Comment by lognaturel** [comment] 2017-06-12 23:56
They should indeed be the same! The two appearances were added in different ODK tools at different times to do the same thing and were consolidated in #386. 

I'll close this for now since it seems the mystery was solved but @mathieubossaert, it would be useful to know what you expected `search` to do and whether you came across any documentation suggesting another behavior.

**Closed as completed by lognaturel** 2017-06-12 23:56 UTC
Labels: bug
