### ISSUE TITLE
Opposite themes in Collect and device when drawing in landscape view and ignoring changes cause wrong colours of dialogues and other parts of Collect

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#5233] opened 2022-08-02 13:11 UTC
**Software and hardware versions** 

Collect v2022.2.3
Android 10, 11, 12

**Problem description**

When there are opposite themes chosen in Collect application and on a device (e.g phone- light mode, Collect- dark mode), sketching an image in Draw widget and ignoring changes applies wrong theme in „Exit Sketch Image” dialogue and later on in information about following questions and other parts of the application.
The same problem occurs in Signature widget.
The same problem occurs also in Annotate widget if the user marks up a landscape view image (the image/photo can be taken or chosen from file).
It seems that opposite themes, drawing in horizontal position and ignoring changes cause this problem. 

https://user-images.githubusercontent.com/56479916/182382486-a148a141-8923-4c5b-9b5b-7ca99e174060.mp4

**Steps to reproduce the problem**

1. In device settings choose light mode.
2. Go to Collect app.
3. Go to Settings → User interface → Theme
4. Choose „Dark theme”.
5. Go to All widgets form.
6. Go to Draw widget.
7. Click „Sketch Image”.
8. Click back button.
9. Click „Ignore Changes” in „Exit Sketch Image” dialogue.
10. Click next or swipe to the next question (if necessary repeat steps 7-10 a few times).

**Expected behavior**

After clicking back button, the user should see the dialogue which is consistent with the chosen theme in the application. After going to the next question, the user should see information about the question consistent with the chosen theme in the application.

**Other information**

Draw and Signature widget -after saving changes in „Exit Sketch Image” dialogue, the problem of changes in following questions doesn’t occur (only wrong colours of dialogues).
Annotate widget- the problem doesn’t occur if an image is in a vertical position.
I’ve also checked Android 11 with Collect v2021.2.0 and it work as expected.

**Comment by seadowg** [comment] 2022-10-05 14:34
@dbemke This looks like a duplicate of https://github.com/getodk/collect/issues/4836 to me. Does that make sense? Will close for now, but reopen if you disagree.

**Closed as completed** 2022-10-05 14:34 UTC
Labels: theme-related

**Comment by dbemke** [comment] 2022-10-05 14:54
@seadowg I don't know if it's a duplicate. I don't know what caused the issue but to reproduce that I needed go to draw/signature widget and ignore changes. I wasn't able to reproduce it with other widgets.

**Comment by seadowg** [comment] 2022-10-05 14:59
As far as we know it's a bug in an Android framework that we can't do much about. It might be that it's easier to reproduce from the signature widget for some reason (although it looks like it's not every time from this issue). Basically, changing theme will sometimes result in some text or an icon using the previous theme.
