### ISSUE TITLE
 Leak after rotating a device in select one form map form when the map bottom sheet is opened

### ISSUE THREAD

**Issue by dbemke** [getodk/collect#6286] opened 2024-07-24 11:33 UTC
#### ODK Collect version
the master version a9c57b94bd7d935e4a62cfd9052066eb15ec7328,
#### Android version
10, 14
#### Device used
Redmi 9T, Pixel 7a
#### Problem description
There’s a memory leak after rotating a device in select one form map form when the map bottom sheet is opened.
![selectOneLeak](https://github.com/user-attachments/assets/08cdeb69-72c1-41bf-a46f-8e35ed462ffe)

#### Steps to reproduce the problem
1. Go to Select one from map form (the demo project).
2. Tap "Select place”.
3. Select a point.
4. Rotate the device.

**Comment by grzesiek2010** [comment] 2024-09-05 10:58
I'm not able to reproduce this issue. The leaks from the screenshot also look like something not directly related to the steps described above. @dbemke @WKobus could one of you try to reproduce?

**Comment by WKobus** [comment] 2024-09-05 12:42
@grzesiek2010 I've tried to reproduce this issue on current master with Android 10 and 14, but I'm also not able to reproduce this.

**Comment by grzesiek2010** [comment] 2024-09-05 13:14
Thanks, so I'm closing the issue.

**Closed as completed by grzesiek2010** 2024-09-05 13:14 UTC
