### ISSUE TITLE
Points entered are reset when select/deselect layer for Mapbox GeoTrace and GeoShape widgets

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/collect#3883] opened 2020-05-29 09:03 UTC
#### Software and hardware versions 
Collect v1.27.x, Android v5.1, 7.1, 10 probably all, device used...

#### Problem description
When testing #3880 I have noticed an issue that turned out to be visible on store version as well.
Points entered are reset when select/deselect layer for Mapbox GeoTrace and GeoShape widgets, gif attached:
![ezgif com-video-to-gif (2)](https://user-images.githubusercontent.com/33342488/83241581-523db500-a19b-11ea-990a-aee6883c0b3a.gif)

#### Steps to reproduce the problem
1. Select Mapbox in Map Settings 
2. Add an offline layer and select it
3. Open GeoTrace/GeoShape widget
4. Input any method and start to record location
5. When some points are already entered change layer to none
Points are gone/ Points entered displayed as 0 in the bottom of the page but polyline/polygon is visible

#### Expected behavior
- Points should be visible
- number of entered points should be visible
- user should be able to delete/save after stopping recording
- the results should be exactly the same as for Google map

#### Other information 
- the same issue is visible when an offline layer is not selected in settings but then is selected after recording points (opposite scenario to described)
- the issue occurs only for Mapbox

**Comment by lognaturel** [comment] 2020-05-29 14:02
Duplicate of #3515. The fundamental issue is with the way that the order of layers is established and maintained. See more of the discussion at https://github.com/getodk/collect/pull/3457#issuecomment-575847471

**Comment by lognaturel** [comment] 2020-08-06 21:45
More details about how this affects users: https://forum.getodk.org/t/collect-location-marker-disappears-on-map-after-sleep/28960/3

**Comment by marenab** [comment] 2020-08-06 23:56
Asking around to see if we can get some Mapboxers to help with this!

**Comment by lognaturel** [comment] 2020-08-07 05:34
Thank you, @marenab!

**Comment by zestyping** [comment] 2020-10-12 21:20
Yes, I'm looking at this issue.  Thanks ODK-bot!

**Comment by grzesiek2010** [comment] 2022-07-14 18:07
This issue does not occur anymore so I'm closing.

**Closed as completed by grzesiek2010** 2022-07-14 18:07 UTC
