### ISSUE TITLE
'Go To Prompt' view is visible without content in RTL languages

### ISSUE THREAD

**Issue by mmarciniak90** [getodk/collect#1977] opened 2018-03-06 14:22 UTC
#### Software and hardware versions 
Collect v1.13.2

#### Problem description
'Go To Prompt' view is visible without content in RTL languages

#### Steps to reproduce the problem
1. User uses RTL languages
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/37036807-a23b5722-2148-11e8-890e-1f8db95c48d6.png">

2. User starts form
3. User clicks on `Go to Prompt` icon
4. View is opened without content
<img height="40%" width="40%" src="https://user-images.githubusercontent.com/3907554/37036845-ca1eb0f4-2148-11e8-9acb-0db04671ca6a.png">

#### Expected behavior
User sees correct view in RTL languages

#### Other information 
Noticed during testing #1958

**Comment by lognaturel** [comment] 2018-03-06 15:15
Duplicate of #1914

**Closed as completed by lognaturel** 2018-03-06 15:15 UTC
